### ISSUE TITLE
Permission.storage.request();   crash on iOS 13

### ISSUE THREAD

**Issue by spirej** [Baseflow/flutter-permission-handler#1016]
Permission.storage.request();   crash on iOS 13

**Comment by JeroenWeener** [comment]
Hi @spirej, thank you for filing your issue!

In order for us to effectively help you, we require some additional information.
Could you provide us with:

- A minimal reproducible code sample
- The output of `flutter doctor -v`
- The version of the plugin you are using (e.g. `10.4.1`)
- The contents of your `Info.plist` file

Without this information, we do not have much foothold to start an investigation into this issue.

You can create a minimal reproducible code sample by creating a new Flutter project (`flutter create temp`) and updating the generated `main.dart` to the point where your issue is apparent. Then you can comment below with the contents of `main.dart` using

\```dart
  your main.dart contents
\```

alternatively, you can share a [GitHub gist](https://gist.github.com/).
