### ISSUE TITLE
locationAlways hangs if location was "Allowed Once" in iOS

### ISSUE THREAD

**Issue by semin-park** [Baseflow/flutter-permission-handler#1018]
## 🐛 Bug Report

Upon requesting `locationWhenInUse`, if the user presses "Allow Once" in iOS, the permission status returns `isGranted`, which, depending on how you interpret, might be a valid response.

However, this becomes a problem when you request `locationAlways` thereafter. If you do request `locationAlways` at this state, the request will hang.

If you go to the Settings and see the real permission status for the app, it'll still show "Ask Next Time Or When I Share", instead of "While Using the App". So from this point of view, I think `locationWhenInUse.isGranted` returning true might be an oversimplification and we might need another state to handle "Allow Once"

### Configuration

**Version:** 10.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by GaelleJoubert** [comment]
I just want to add something about this issue (because I have been strugling to come to this conclusion).
The fact that the request "hang", makes the app to crash on ipad !
I does work on iphones, but it crash on ipad.
So I you are looking for something that makes your app crash only on ipad but not on iphones, this is it !

**Comment by yerkejs** [comment]
There is an open PR from me: https://github.com/Baseflow/flutter-permission-handler/pull/1028
