### ISSUE TITLE
await Permission.phone.status Bug report

### ISSUE THREAD

**Issue by SimonTellier** [Baseflow/flutter-permission-handler#1030]
Hello,
I work on a samsung phone usually and everything works.
But I tested the phone rights on a Nexus 5 emulator and I have a problem.
When I look at the phone right after validating the right with the popup (I did look in the settings if it was true) it tells me "(await Permission.phone.status).isGranted == false" but when I do "(await Permission.phone.request()).isGranted == true" without getting a popup

![Capture d’écran 2023-04-19 à 11 36 56](https://user-images.githubusercontent.com/51329066/233034651-ee29659a-adfb-4c3b-8356-13296d2b84a2.png)

**Comment by JeroenWeener** [comment]
Hi @SimonTellier, thank you for taking the time to file this issue!

I am not sure if I completely follow what you are saying. Let me try to phrase my interpretation and assumptions about your question. Then you can tell me if I understood correctly.

---
You are testing your application on a Nexus 5 emulator. This application uses the `permission_handler` plugin for requesting the `phone` permission.
Before you run the application, you make sure the phone permission is already granted to the application by checking for it in the Android settings. Then you boot up your application.

Somewhere in your code, you are calling

```dart
(await Permission.phone.status).isGranted
```

You expect this to return `true`, since that is what the Android settings are telling you. However, the invocation returns `false`. Just to be sure, you try to request the permission by calling

```dart
(await Permission.phone.request()).isGranted
```

You expect a dialog to show, asking the user for permission, since apparently the permission is not granted yet, despite the Android settings saying it was. However, the invocation returns `true`, and no dialog is shown.

---

Please let me know if this summary is correct or at which points I am mistaken. It is important to get a clear picture of the situation that arises so we know what to look for. Additionally, some extra information is usually extremely helpful in identifying the issue. Could you therefore provide me with:

- The version of the plugin you are using
- A minimal reproducible code sample
- The contents of your `AndroidManifest.xml` file
- The output of `flutter doctor -v`

You can quickly create a minimal reproducible code sample by running `flutter create temp` and updating the `main.dart` file. You can then post its contents here or link us a [Github Gist](https://gist.github.com/).
