### ISSUE TITLE
android SDK 30+ not get READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by lucky97-dev** [Baseflow/flutter-permission-handler#1050]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by julianfalcionelli** [comment]
I think it's the same as https://github.com/Baseflow/flutter-permission-handler/issues/1026, adding the `MANAGE_EXTERNAL_STORAGE` will solve this but may be got rejected by the PlayStore, since according to their policies permission must be used for some specific use cases, more info in: https://support.google.com/googleplay/android-developer/answer/10467955?sjid=7357720668209546494-EU#alternatives&zippy=%2Crecommended-privacy-friendly-alternatives%2Cinvalid-uses

**Comment by JeroenWeener** [comment]
Hi @lucky97-dev, thanks for filing this issue!

This looks related to #955. As mentioned there, before Android 13 (API 33), you need to request `READ_EXTERNAL_STORAGE` in the `androidmanifest.xml`. Starting with API 33, you should request granular media permissions. For more information, please have a look at https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions.
