### ISSUE TITLE
What about supporting "Show on top" permission.

### ISSUE THREAD

**Issue by busslina** [Baseflow/flutter-permission-handler#1055]
I don't even know if it is possible to get this permission programatically

**Comment by mvanbeusekom** [comment]
The "Show on top" permission is also known as "System Alert Window" on Android (supported since 7.1.0) and "Critical Alerts" on iOS (supported since 8.1.0). 

An example on how to request these permissions might look something like this:

```dart
Future<PermissionStatus> requestShowOnTop() {
  if (defaultTargetPlatform == TargetPlatform.android) {
    return Permission.systemAlertWindow.request();
  } else if (defaultTargetPlatform == TargetPlatform.iOS) {
    return Permission.criticalAlerts.request();
  } else {
    return Future.value(PermissionStatus.denied);
  }
}
```
I will close this issue as I assume this answers your question. Feel free to leave a comment providing more details regarding your issue and I will be happy to re-open it.

**Comment by busslina** [comment]
Thank you
