### ISSUE TITLE
Is there any way using which we can know user have allowed apple health permission or not?

### ISSUE THREAD

**Issue by ketanphpdots** [Baseflow/flutter-permission-handler#1056]
### Feature required

health: ^6.0.0

### Platforms affected
- [ ] :iphone: iOS
- [ ] :robot: Android

health plugin is used to fetch data from Apple Health SDK to flutter app.

For which user need to request Authorization from user and after the user's action need to know the status of it.

So, Can you please add this feature in the upcoming release ?

**Comment by TimHoogstrate** [comment]
Dear @ketanphpdots,

We assume that you would like to know if a user has authorised the app for Apple Health data. Apple HealthKit will not disclose if READ access has been granted for a data type due to privacy concern. Does this answer you question? So we think that we cannot include this as a feature in one the upcoming releases. Therefore, I close this issue. Feel free to reopen an issue if this does not solve your issue or if we misunderstood your issue. If we misunderstood, please add some more detailed information regarding your problem and preferred outcome.
