### ISSUE TITLE
[Bug]: Permissions.storage.request() always return  PermissionStatus.denied

### ISSUE THREAD

**Issue by dmcoding** [Baseflow/flutter-permission-handler#1084]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

![Captura de pantalla 2023-07-04 a la(s) 12 16 36 a m](https://github.com/Baseflow/flutter-permission-handler/assets/22920594/2c7fd5bf-abe6-4d2a-8050-a5746dde5bcc)

Last use compile sdk version 32 and currently change this sdk version to 33, after with device with sdk <= 32 present error when select allow to permission

### Expected results

I expected grented result

### Actual results

Only I receive null and with debug mode verify that return null value and receive default value PermissionStatus.denied from request method

### Code sample

<details><summary>Code sample</summary>

```dart
Future<PermissionStatus> requestPhotosPermission() async {
    final AndroidDeviceInfo androidInfo = await DeviceInfoPlugin().androidInfo;

    if (androidInfo.version.sdkInt <= 32) {
      /// use [Permissions.storage.status]
      return await Permission.storage.request();
    } else {
      /// use [Permissions.photos.status]
      return await Permission.manageExternalStorage.request();
    }
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

permission_handler: ^10.4.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/danielmarin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/danielmarin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/danielmarin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)            
    • AGS3 W09 (mobile) • 47BNU21115201453 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 13.4 22F66 darwin-arm64 (Rosetta)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @dmcoding,

Of course I am not familiar with the exact needs of your application so I am making some assumptions here, please don't feel offended. 

The `READ_EXTERNAL_STORAGE` permission is marked deprecated since Android 10 (API 29). Starting from Android 10 it is recommended to use the Media Store API (using the `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` permissions). Google has documented this in the "[Access media files from shared storage](https://developer.android.com/training/data-storage/shared/media#storage-permission)" article.

Since August 2021 apps targeting Android SDK 30 are required to use the media storage API for devices running Android 11 (API 30) and higher, otherwise apps will not be accepted to the Play Store. This means that the "old" `READ_EXTERNAL_STORAGE` permissions will only work on devices running Android 10 or lower (note that for Android 10 you'd have to specify the `android:requestLegacyExternalStorage="true"` attribute as part of the `application` element in the AndroidManifest.xml file). More details can be found [here](https://stackoverflow.com/a/63365334/5167831) and [here](https://stackoverflow.com/a/63365276/5167831).

I also noticed that the sample code is requesting `manageExternalStorage` permission on Android 33 and higher. To request this permission the application needs a specific exempt from Google is it needs to be deployed to the Google Play Store. In cases where the application only need access to photos, videos or audio files it is recommended to request these specific permissions using:

- `Permission.photos.request()`
- `Permission.video.request()`
- `Permission.audio.request()`

Hopefully this information provides a better understanding of the storage permissions. Since the plugin is behaving as expected I will close this issue for now.
