### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by AlexBacich** [Baseflow/flutter-permission-handler#1124]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

There is Podfile describing which permissions are used. For Location however we always request all three types: 

       ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

Is it possible to exclude from permissions locationAlways? Only have locationWhenInUse. Maybe feature request thing. 

### Version

10.4.3

**Comment by mvanbeusekom** [comment]
Hi @AlexBacich,

The definitions in the `ios/Podfile` are macros that will inform the build system if logic for accessing the location information should be included in the final binary or not. The reason we do this is because Apple wil run static code analysis on the .ipa that is uploaded to the App Store and when they detect there is code in the binary that references the location SDK it will reject the upload.

Since you do want to make use of the location services in your app, you can set the `PERMISSION_LOCATION` macro to `1` which includes the necessary logic. Internally the logic will check the `ios/Runner/Info.plist` to determine which permissions should actually be supported. If the application only needs `locationWhenInUse` add the following to the `ios/Runner/Info.plist` file:

```xml
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
```

If the application needs both (`locationWhenInUse` and `locationAlways`) make sure both permissions are listed in the `ios/Runner/Info.plist` file, like so:

```xml
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>This app needs access to location when in the background.</string>
```

Note that you cannot only request `locationAlways` permission.

Hope this answers your question. I will close the issue for now, however feel free to leave a follow up comment and I will have a look at it.
