### ISSUE TITLE
[Feature request]: can we just drop windows support for now since it crashes on win7 and later

### ISSUE THREAD

**Issue by jwang0512** [Baseflow/flutter-permission-handler#1228]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [X] Windows

### Use case

this bug existed for almost 1 year, from version 9.2 to 11.0.1

### Proposal

-

**Comment by TimHoogstrate** [comment]
Dear @jwang0512,

Can you elaborate a bit on the subject? Can you paste some minimal reproducible code or steps to reproduce to this issue? Furthermore, can you add the output of `flutter doctor -v` and perhaps the stack trace so that we can investigate why it is crashing in your case? 

Kind regards,

**Comment by jwang0512** [comment]
Dear @TimHoogstrate 
Sorry, my bad. reinstalled my os and now it works grate.
Apologize for my hasty.
