### ISSUE TITLE
[Feature request]: Request permission for particular folder

### ISSUE THREAD

**Issue by msarkrish** [Baseflow/flutter-permission-handler#1231]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Use case

In Android latest version for accessing particular folder files, we have get permission for the particular folder from the user.

### Proposal

Need option to get permission like this

![a870e2da97eb2345ca66091c22521ff30d2d7224](https://github.com/Baseflow/flutter-permission-handler/assets/45334931/b7b2546d-3605-4094-b91c-2836bbcebf8a)

**Comment by TimHoogstrate** [comment]
Dear @msarkrish,

Can you elaborate a bit on the subject? Can you also point us to some relevant documentation?

Kind regards,

**Comment by msarkrish** [comment]
@TimHoogstrate 

I wanted to read files from a particular folder on Android. For that, I have to get permission from the user. Can you make this permission request in the Permission Handler plugin?


I have added a video recording for your reference.

https://github.com/Baseflow/flutter-permission-handler/assets/45334931/07930dce-28dd-4e74-84df-80649d5e5353

**Comment by TimHoogstrate** [comment]
Dear @msarkrish,

I don't understand what you mean. Can you point us to some relevant Android documentation? You can request permission for storage. 

Kind regards,

**Comment by mvanbeusekom** [comment]
Hi @msarkrish and @lucidBrot,

I have looked into the issue and this doesn't seem related to the Android Permission API which is the core problem the permission_handler is trying to solve. 

This issue seems related (as mentioned by @lucidBrot ) to showing a native file picker and returning the path to that particular file (with the necessary permissions). In Android this is indeed done via the `ACTION_OPEN_DOCUMENT_TREE` intent which will open the file picker, lets users select a file and return the path of the selected file to the application (with the necessary read and write permissions).

This functionality is so different from the standard resource permissions that we feel it doesn't belong in the permission_handler plugin. It is not that difficult to write a custom method channel to access the native api yourself (see Flutter [documentation](https://docs.flutter.dev/platform-integration/platform-channels)) and it looks like the [shared-storage](https://alexrintt.io/shared-storage/Usage/Storage%20Access%20Framework/) @lucidBrot  mentioned package will also solve this issue. 

Since we feel this feature doesn't belong in the permission_handler plugin I am going to close this issue.

**Comment by msarkrish** [comment]
Thank you, @mvanbeusekom @lucidBrot @TimHoogstrate . Yes, my requirement is not related to the permission handler. Sorry for the wrongly created issue.
