### ISSUE TITLE
[Feature request]: Implement full screen intent android permission request

### ISSUE THREAD

**Issue by dnkoulouris** [Baseflow/flutter-permission-handler#1338]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Use case

For apps that contain Videocalls or Alarms and target Android 14 and above, request for USE_FULL_SCREEN_INTENT permission is mandatory.
https://developer.android.com/reference/android/Manifest.permission#USE_FULL_SCREEN_INTENT
https://developer.android.com/training/permissions/requesting-special

### Proposal

Add `Permission.useFullScreenIntent`

**Comment by dnkoulouris** [comment]
Hi @mvanbeusekom, 

the problem is that in order for the app to be accepted at play store, the permission must be requested manually by the user. This is a new limitation of the Android 14. The other solution is to use platform channels and implement native code.

**Comment by mvanbeusekom** [comment]
Can you provide additional documentation on how to do so?

I cannot find it in the two links you have send.

**Comment by dnkoulouris** [comment]
https://source.android.com/docs/core/permissions/fsi-limits

**Comment by yahya489** [comment]
Google play store is asking developers to ask permission manually on android 14 

USE_FULL_SCREEN_INTENT

**Comment by tommy-elliott-awh** [comment]
The requirement seems to be that ONLY if your app uses alarm clock or calling features, your app can be exempted from needing to manually request the permission from the user and can still be granted the permission automatically on app install - this is specified in a new App Content section in Google Developer Console.  However, if your app isn't an alarm clock or calling app, you must request the permission from users for it to be granted.  The app will crash if permission is not requested and granted before its use.  The stated timeframe is May 31st 2024 for when this requirement change went into effect.  The Learn more link goes to https://support.google.com/googleplay/android-developer/answer/14016515?hl=en which explains the requirements in more specific details.
![Cropped Screenshot 2024-06-24 at 12 29 32 PM](https://github.com/Baseflow/flutter-permission-handler/assets/60673819/277bf49a-fac0-4274-8fdc-1a68c26d6831)

**Comment by mvanbeusekom** [comment]
I have been looking deeper into the documentation and it seems like Android will handle requesting the permission automatically if the `` key is part of the AndroidManifest.xml (from [Android documentation](https://developer.android.com/reference/android/app/NotificationManager#canUseFullScreenIntent())):

> Returns whether the calling app can send fullscreen intents.
>
> From Android [Build.VERSION_CODES.UPSIDE_DOWN_CAKE](https://developer.android.com/reference/android/os/Build.VERSION_CODES#UPSIDE_DOWN_CAKE), apps may not have permission to use [Manifest.permission.USE_FULL_SCREEN_INTENT](https://developer.android.com/reference/android/Manifest.permission#USE_FULL_SCREEN_INTENT). If permission is denied, notification will show up as an expanded heads up notification on lockscreen.
>
> To request access, add the [Manifest.permission.USE_FULL_SCREEN_INTENT](https://developer.android.com/reference/android/Manifest.permission#USE_FULL_SCREEN_INTENT) permission to your manifest, and use [Settings.ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT).

The only thing developers need to do is have some logic to ensure the permission is granted or not before executing the FSI intent. This seems something more suitable for plugins that actually execute full screen intents to build in and not something for the permission_handler to manage. Especially since there is no option to explicitly request  the permission, which would result into strange behavior and unexpected results in the current API.

For now I will go ahead and close this issue. Please let me know if my assumptions regarding Android automatically requesting the permission are incorrect (including documentation) and I will be happy to reconsider.

**Comment by cshong87** [comment]
https://source.android.com/docs/core/permissions/fsi-limits

Documentation in above link clearly mention the following:

> Upon installation, the Google Play Store revokes the full-screen intent (FSI) permission for apps that do not have calling or alarm functionalities.

This mean when installing apps that do not have calling or alarm functionalities, Google Play Store will revoke the full-screen intent permission.

So, I think you need to look into this.

**Comment by mil84** [comment]
This is an extremely confusing topic, because it's poorly documented and most explanations are ambiguous and/or contradicting - both by Google and most stackoverflow posts.

This is how it works by my research (just wasted the whole day on this stupid shit Google!):

1. On Android 13 and less, all apps gets this permission granted automatically and that's it
2. On Android 14, it get's complicated:

- all apps will be automatically granted this permissions after the install
- but immediately after install Google Play app will perform check on background (it checks the FULL_SCREEN_INTENT declaration form in Google Play) and if you declared your app is not alarm app, then FULL_SCREEN_INTENT permission gets literally immediately "un-granted" on background!

That sucks big time - because it's not only very confusing, but also makes it impossible to test in debug release when developing app - because as I've said, each and every app gets this permission automatically granted immediately after install - and since you usually test just a debug release, Google Play app is not performing the check of declaration form FULL_SCREEN_INTENT, and hence not removing the permission => app behaves completely inconsistently!

Freaking Googlers, took me whole day to figure this out, they don't even bother to mention this in their docs.

Now what you need to do:

1. Always declare FULL_SCREEN_INTENT in manifest
2. And then if your app is not alarm clock, then you must MANUALLY launch intent Settings.ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT opening phone settings screen to get that permission - or your app won't work. Don't get fooled you're having no issues in debug mode without doing this step - it must be done in release mode

**Comment by patrick-billingsley** [comment]
Why was this closed? I cannot currently release my android app due to the new special permissions around USE_FULL_SCREEN_INTENT. I cannot remove this intent as my app has audio/video calling and crashes if I remove it. I can request the permission easily but currently have no way to check if it is already granted. This results in prompting the settings screen every time the app runs.

**Comment by lilole** [comment]
> For now I will go ahead and close this issue. Please let me know if my assumptions regarding Android automatically requesting the permission are incorrect (including documentation) and I will be happy to reconsider.

@mvanbeusekom We still need to be able to check if this permission is granted. The code is already done and ready to go. More than one Flutter project in the world needs this right now.

After you made the comment above, there were valid new comments with good docs. Please help.
