### ISSUE TITLE
My app will not build when using this package in conjunction with Cloud Firestore

### ISSUE THREAD

**Issue by GroovinChip** [Baseflow/flutter-permission-handler#207]
## 🐛 Bug Report

When using the latest version of both packages:
```
cloud_firestore: ^0.13.1
permission_handler: ^4.2.0+hotfix.3
```

My app will not build. Stack trace:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.
```

I am using all the appropriate AndroidX requirements.

### Expected behavior
App should build and run

### Reproduction steps
Use Cloud Firestore in a project that uses `permission_handler`

### Configuration

**Version:**  `permission_handler: ^4.2.0+hotfix.3`

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @GroovinChip, 

Thank you for submitting this issue. The problem here is that the `cloud_firestore` plugin and the `permission_handler` use different versions of the `androidx.core.core` library. The `cloud_firestore` plugin relies on version 1.0.0, while the `permission_handler` is working with version 1.1.0. 

The way to solve this problem is to manually configure the dependency resolution in your `build.gradle` file (the version directly in your `android` folder, so not the one in your `android/app` folder).

To do so add the following code to as direct child of the `buildscript` object:

```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }

            if (details.requested.group == 'androidx.core'
                    && !details.requested.name.contains('androidx') ) {
                details.useVersion "1.1.0"
            }
        }
    }
}
```

Please also have a look at this answer on Stack Overflow which contains more detailed information: https://stackoverflow.com/a/59223586/5167831

**Comment by GroovinChip** [comment]
This did the trick, thank you!
