### ISSUE TITLE
Task 'assembleAarRelease' not found in root project 'permission_handler'

### ISSUE THREAD

**Issue by Chinnu32** [Baseflow/flutter-permission-handler#208]
I am new to Flutter and facing the following issue when using the permission_handler.

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'permission_handler'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Finished with error: The plugin permission_handler could not be built due to the issue above.
```

**Comment by tackelua** [comment]
@Chinnu32  how about your problem?

I have met the same problem when trying ussd_service
https://pub.dev/packages/ussd_service#-example-tab-

`Task 'assembleAarRelease' not found in root project 'permission_handler'.
`

**Comment by mvanbeusekom** [comment]
@Chinnu32 could you provide a bit more information on what you are trying to accomplish? 

Are you referencing the `permission_handler` plugin in your own App? Or are you trying to compile the plugin it self? Based on the supplied information I am unable to reproduce the error.

It would be ideal if you could provide an example App demonstrating the issue. Also please provide the following information:

- Which Flutter version you are using;
- Which version of the `permission_handler` you are using;
- Which steps do you take that lead to this error (e.g. which `flutter` commands do you run and from which folder in your project).

We would be happy to help if you could provide more details.

**Comment by mvanbeusekom** [comment]
Closing issue due to lack of response.

**Comment by singh-preet** [comment]
Task 'assembleAarRelease' not found in root project 'audioplayer'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 997ms

Finished with error: The plugin audioplayer could not be built due to the issue above.

**Comment by FaheemuddinKhan** [comment]
Delete the .gradle folder inside the android folder ie android>.gradle

In the project build.gradle file, upgrade ur class path appropriately based on the blog in the link above, e.g i upgraded to classpath 'com.android.tools.build:gradle:4.0.1'

Upgrade the distribution url too. Its in android>gradle>gradle-wrapper.properties file appropriately. e.g i upgraded it to distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip 

You can invalidate caches and restart your android studio. Make sure you have a good internet connection because it will download the new gradle files.

**Comment by ankurrup83** [comment]
I am also geting the same issue
