### ISSUE TITLE
Once calling openAppSettings, there is no way to find out you are back on your app.

### ISSUE THREAD

**Issue by AlexandreRoba** [Baseflow/flutter-permission-handler#219]
## 🏗 Enhancement Proposal

When calling onAppRequest, the Permission settings might change... When I'm done changing the permissions and go back to my app, There is no callback to tell to indicate the settings have changed.
We chould check the permission again but as there is no callback or async result telling me the use has gone back to my app, I do not know when to call this refresh.

 var result = await PermissionHandler()
                                      .openAppSettings();
//Refresh screen that display the settings on my app
checkPermissionAndUpdateWidgetSet() //This is called right after displaying the AppSettings... Not when coming back from the app settings... A bit like the navigator.push works. I can await the push and leverage the poped value....

### Platforms affected (mark all that apply)
- [x ] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @AlexandreRoba, thank you for thinking with us.

The problem is a bit the the native SDK's don't allow us to register a callback method that is called when a user returns. 

- On iOS we use the `open` method which allows registering a callback which will inform us if the URL was opened successfully or not. Unfortunately this doesn't tell us anything about it the user came back to the app or make any changes (see the [iOS docs](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open) for more info);
- On Android we send the `ACTION_APPLICATION_DETAILS_SETTINGS` intent. Also here there is no way to register any callback about returning or being informed about changes to the settings.

As far as I understand (and how I solved it several times when doing native iOS development), is that you listen for the App getting focus again. When you show the App Settings your app loses focus. When the user finishes up in the settings and moves back to your App, it will get focus again which would trigger a callback and that would be an ideal place to check for permissions again. With Flutter you can possible make use of the `AppLifecycleState` (see [here](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html) for more detaisl) to get notified when the user comes back to the App. 

Since this is something that is related to the state of the App, it is difficult and not really the right place to implement this in the permission_handler plugin.

If you have any other ideas or suggestions please let me know.

**Comment by TNorbury** [comment]
Here is what I'm doing in an app I'm working on. `onReturn` is provided as an argument to the method this is in. Works well for me!
```dart
bool settingsOpened = await openAppSettings();
if (settingsOpened) {
  BasicMessageChannel<String> lifecycleChannel = SystemChannels.lifecycle;
  lifecycleChannel.setMessageHandler((msg) {
    // When the app is resumed, we'll stop listening to lifecycle changes
    if (msg.contains("resumed")) {
      lifecycleChannel.setMessageHandler(null);
      onReturn();
    }

    return;
  });
}
```
