### ISSUE TITLE
Why PermissionStatus.disabled removed?

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-permission-handler#224]
## 🔙 Regression

I use in my app the `PermissionStatus.disabled` value. Your new update will crash my app now. Why do you remove this enum item? And is it possible to restore it?

**Version:** 4.2.0+hotfix.3

**Comment by mvanbeusekom** [comment]
Hi @bambinoua, 

We have removed `PermissionStatus.disabled` because it was compliant with Android's and iOS's best practices. 

First of all the `PermissionStatus.disabled` really isn't a permission status, it is the status of the location services. It describes is the location services are enabled or not. For this functionality we have a separate method `checkServiceStatus`. 

Second the `PermissionStatus.disabled` prevented developers to request permissions when the the location services are disabled. This is something we received a lot of complaints about and as mentioned doesn't comply with the best practices.

In the next version of the plugin we will try to add functionality on Android to ask the end-user to turn on location services with out having to leave the App.

Hope this helps, sorry to hear you App is breaking. For now you could switch back to version 4.2.0+hotfix3, which will allow you to take time and apply the necessary fixes to your app.
