### ISSUE TITLE
Location service is disabled but returns status as granted

### ISSUE THREAD

**Issue by GursheeshSingh** [Baseflow/flutter-permission-handler#248]
I am using the latest version of the library: **^5.0.0+hotfix.2**

* I have disabled the location services in my android emulator

![image](https://user-images.githubusercontent.com/31126864/78017006-3f5c5f00-7369-11ea-95c0-fa47c1d24fa5.png)

* However location is granted in application settings

![image](https://user-images.githubusercontent.com/31126864/78017223-8f3b2600-7369-11ea-81a6-c170a0a97497.png)

When i do -

    PermissionStatus permissionStatus =
        await Permission.locationWhenInUse.status;

    print(permissionStatus.toString());

It prints - 

I/flutter ( 7856): PermissionStatus.granted

**Platform:** 
- [ ] :robot: Android

## Expected behaviour 

Previously it used to returned PermissionStatus.disabled so I would open the location setting screen.

So it should either return PermissionStatus.disabled or open Location settings

**Comment by mvanbeusekom** [comment]
We have removed PermissionStatus.disabled because it was not compliant with Android's and iOS's best practices.

First of all the PermissionStatus.disabled really isn't a permission status, it is the status of the location services. It describes is the location services are enabled or not. 

Second the PermissionStatus.disabled prevented developers to request permissions when the the location services are disabled. This is something we received a lot of complaints about and as mentioned doesn't comply with the best practices.

So if you want to know if the location services are enabled you can use the following code:
```
Permission.location.serviceStatus.isEnabled
```

More info on the best practices can be found on these locations:
- https://developer.android.com/distribute/best-practices/develop/runtime-permissions
- https://developer.android.com/training/permissions/requesting

**Comment by GursheeshSingh** [comment]
Thank you for the quick response.
I wasn't aware about -
`Permission.location.serviceStatus.isEnabled`

**Comment by MahdiGharooni** [comment]
thank you.
In my case **Permission.location.serviceStatus** is disabled and I can't use from location correctly.
How can I set **Permission.location.serviceStatus** enable??
