### ISSUE TITLE
  Status is undetermined 

### ISSUE THREAD

**Issue by bakboem** [Baseflow/flutter-permission-handler#257]
## 💬 Questions and Help
I can get  Permission And there's no problem running it.
but,   Status is always undetermined. 
What should I do?

**Comment by mvanbeusekom** [comment]
Are you only checking permissions? Do you request permissions? 

Maybe you could give use a little more information to work with? Some example code (small app to that reproduces the problem) would be really helpful

**Comment by bakboem** [comment]
PermissionStatus is always called the disabled.

` Future<PermissionStatus> requestPermission(Permission permission) async {
    return await permission.status;
  }

  Future<ServiceStatus> checkLocationServiceStatus(
      Permission permission) async {
    return permission == Permission.location
        ? Permission.location.serviceStatus
            .then((serviceStatus) => serviceStatus)
        : permission == Permission.locationAlways
            ? Permission.locationAlways.serviceStatus
                .then((serviceStatus) => serviceStatus)
            : permission == Permission.locationWhenInUse
                ? Permission.locationWhenInUse.serviceStatus
                    .then((serviceStatus) => serviceStatus)
                : null;
  }

  Future<bool> checkLocationPermisson() async {
    List<bool> canuse;
    await getLocationPermisson()
        .then((list) => list.forEach((permission) async {
              if (await permission.isGranted) canuse.add(true);
            }));
    return canuse.contains(true) ? true : false;
  }

  Future<List<Permission>> getLocationPermisson() async {
    List<Permission> permissionList =
        Permission.values.where((Permission permission) {
      if (Platform.isIOS) {
        return permission == Permission.location ||
            permission == Permission.locationAlways ||
            permission == Permission.locationWhenInUse;
      } else {
        return permission == Permission.location ||
            permission == Permission.locationAlways ||
            permission == Permission.locationWhenInUse;
      }
    }).toList();

    return permissionList;
  }`

**Comment by bakboem** [comment]
service status is always called  =>  ServiceStatus.disabled


` Future<PermissionStatus> requestPermission(Permission permission) async {
    return await permission.status;
  }

  Future<ServiceStatus> checkLocationServiceStatus(
      Permission permission) async {
    return permission == Permission.location
        ? Permission.location.serviceStatus
            .then((serviceStatus) => serviceStatus)
        : permission == Permission.locationAlways
            ? Permission.locationAlways.serviceStatus
                .then((serviceStatus) => serviceStatus)
            : permission == Permission.locationWhenInUse
                ? Permission.locationWhenInUse.serviceStatus
                    .then((serviceStatus) => serviceStatus)
                : null;
  }

  Future<bool> checkLocationPermisson() async {
    List<bool> canuse;
    await getLocationPermisson()
        .then((list) => list.forEach((permission) async {
              if (await permission.isGranted) canuse.add(true);
            }));
    return canuse.contains(true) ? true : false;
  }

  Future<List<Permission>> getLocationPermisson() async {
    List<Permission> permissionList =
        Permission.values.where((Permission permission) {
      if (Platform.isIOS) {
        return permission == Permission.location ||
            permission == Permission.locationAlways ||
            permission == Permission.locationWhenInUse;
      } else {
        return permission == Permission.location ||
            permission == Permission.locationAlways ||
            permission == Permission.locationWhenInUse;
      }
    }).toList();

    return permissionList;
  }`

**Comment by bakboem** [comment]
Yes, I requested permission, It only happens in locationPermission.
//
<img width="587" alt="截屏2020-04-10 下午8 45 02" src="https://user-images.githubusercontent.com/19185416/78988550-355a0d80-7b6c-11ea-962e-e5cd5d0f13fe.png">

**Comment by mvanbeusekom** [comment]
First of all to request the location service status (e.g. are the location services on the device enabled) you can simply use the following code:

```dart
if (await Permission.location.serviceStatus.isEnabled) {
   // Location services are enabled...
}
```

There is no need to test for `location`, `locationAlways` or `locationWhenInUse`. Location services are either on or off no matter which permissions you need.

Your `getLocationPermisson` doesn't have to be a `Future` since is only runs synchronous code. Also why not simply update it to a `const` array and use this array when necessary? The way you implemented it now looks overly complex.

```dart
const locationPermissions = <Permission> [
  Permission.location,
  Permission.locationAlways,
  Permission.locationWhenInUse,
];
```

Question is even if you would really need to request all of the location permissions. If you don't mind which particular permission you would need (e.g. you don't specifically need to have location updates in the background) you could simply request permissions for the location value. In that case the permission_handler will figure out which permission to ask for depending on what is listed in your `AndroidManifest.xml` and `Info.plist` files. Meaning the following would suffice:

```dart
Future<bool> checkLocationPermission() async {
  return await Permission.location.status.isGranted;
  // or you could use the shorter version:
  // return await Permission.location.isGranted;
}
```

You can also optimize your `requestPermission` method by removing the `then` method. And since you are not directly using the status in this method there is also no need to await it here. So you could change it to:

```dart
Future<PermissionStatus> requestPermission(Permission permission) {
    return permission.request();
}
```

Which leaves almost nothing so I would say loose the whole method and call the permission directly when needed. So instead of calling `final status = await requestPermission(Permission.location)` you could do `final status = await Permission.location.request()`.

I hope this helps a bit. You should be able to clean up your code quite a bit which hopefully solves your problem. If it still persists please submit a bit more of your code so I can analyze it more detailed. Or make a reproducible example which you can share.

**Comment by bakboem** [comment]
Thank you very much for taking the time to reply to me. Your suggestion is very good!
 I know what you mean, and I want to make it easier.
However, there are three options for location services. 
I need to implement different methods according to different location permissions
Like your example, I want users to see all their status view,
<img width="569" alt="截屏2020-04-11 上午8 44 30" src="https://user-images.githubusercontent.com/19185416/79029733-adf2b580-7bd0-11ea-8201-2b1e99c19fbb.png">

click child widget returns PermissionStatus and PermissionServiceStatus. 
<img width="569" alt="截屏2020-04-11 上午9 01 59" src="https://user-images.githubusercontent.com/19185416/79030260-1cd10e00-7bd3-11ea-9497-5ee339189adc.png">

Even though I changed my permissions on the settings page, there seems to be no dynamic feedback,

always return ServiceStatus.disabled.
![IMG_2924](https://user-images.githubusercontent.com/19185416/79030437-e6e05980-7bd3-11ea-86cf-2180d522bc3b.jpg)

Maybe I didn't configure it correctly. I'll find out the reason again. Thank you again for your reply. Thank you
