### ISSUE TITLE
Permission.location.status doesnt differentiate between "while in use" and "always"

### ISSUE THREAD

**Issue by gkrawiec** [Baseflow/flutter-permission-handler#300]
## 🚀 Feature Requests

As is, the Permission.location.status response is `granted` for both `While In Use `and for `Always`.
It should differentiate between the 2.

### Describe the feature
please add more options to the permission status enum so that we can get the exact permission with a single call.

**Comment by Zhaojing0987** [comment]
Try Permission.locationAlways.status or Permission.locationWhenInUse.status

**Comment by MilesAdamson** [comment]
I have found this works as expected for iOS 12 and lower, but not iOS 13.

This returns `true` on iOS 13, when you can open up the settings and see location is set to while in use. on iOS 12 it returns `false`, and properly reflects what you see in the apps settings.

```
  static Future<bool> hasPermission(PermissionGroup permissionGroup) async {

    PermissionStatus permissionStatus =
        await PermissionHandler().checkPermissionStatus(permissionGroup);

    return permissionStatus == PermissionStatus.granted;
  }
```

Haven't found any issues on Android yet

**Comment by JDDV** [comment]
Hi @gkrawiec, If you use the newest version of the plugin (version `^8.1.4+2`) it should work as it's supposed to do.
To request the `locationAlways` permission, you must first grant permission to the `locationWhenInUse` permission, choosing the option `Allow While Using App`when the request dialog pops up. If this permission is `granted` you can ask for the `locationAlways` permission, which will prompt you a dialog with the options to either keep the `When in use` permission, or change it to `always`.

If you upgrade to the newest version of the `permission_handler`, keep in mind that you should also update the podfile as stated in the `README` of the newest version of the `permission_handler` since there has been some changes since version `^8.0.0`.

I will close this issue for now, but feel free if you have any questions left.
