### ISSUE TITLE
App crashes when debugging with breakpoints

### ISSUE THREAD

**Issue by JustChris** [Baseflow/flutter-permission-handler#361]
## 🔙 Regression

When in debug mode and with a breakpoint set. When hovering over variables e.g. the 'isGranted' bool, the app crashes.

### Old (and correct) behavior
Debugging worked flawlessly 

### Current behavior
When in debug mode and with a breakpoint set. When hovering over variables e.g. the 'isGranted' bool, the app crashes.

### Configuration

**Version:** 5.0.1+1

**Platform:** 
- [ x ] :iphone: iOS
- [ x ] :robot: Android

**Comment by JDDV** [comment]
Hi @JustChris, I just tested this to see if it would crash. But it looks like this is not plugin related, I can't reproduce the issue you have. It might have to do with your code maybe, can you provide the part of your code you're trying to debug?

Maybe you can test it the same way how I tested it, to see whether it's the plugin or your code that's causing your problem. 
I created a flutter project (the standard incremental counter) and write in the _incrementalCounter() method the following lines:

```
void _incrementCounter() async {
    Permission permission = Permission.camera;
    bool isDenied = await permission.isDenied;

    if(isDenied){
          print('isDenied');
        } else {
          print('isGranted');
        }
}
```

I debugged this, and the value of isDenied turned out to be as expected, and the app didn't crash.
Can you check if the debugging goes as planned by using this code?
