### ISSUE TITLE
Flutter 1.17.5 build failed

### ISSUE THREAD

**Issue by WxqKb** [Baseflow/flutter-permission-handler#364]
### I created a new project and introduced the "permission_handler", and ran directly with an error.
My flutter version is 1.17.5. It's fully compatible AndroidX.
Thank you very much！

![image](https://user-images.githubusercontent.com/48406291/89968278-ff49a900-dc85-11ea-9a75-61f941d9aab3.png)

![image](https://user-images.githubusercontent.com/48406291/89968308-18525a00-dc86-11ea-8f8d-b9d55b18c408.png)

**Version:** ^5.0.1+1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by akinncar** [comment]
+1

**Comment by mvanbeusekom** [comment]
@WxqKb, @akinncar, this is probably because your app is still using Gradle version 3.4.1 to build the Android project. The permission_handler plugin relies (just like Flutter projects created with `flutter create` since version 1.12.x) on Gradle version 3.5.0. 

To update your Gradle version please change the following (the mentioned paths assume you are in the root of your Flutter project):

1. In the file `android/build.gradle` update the line `classpath 'com.android.tools.build:gradle:3.4.1'` to  `classpath 'com.android.tools.build:gradle:3.5.0'`;
2. In the file `android/gradle/wrapper/gradle-wrapper.properties` make sure the `distributionUrl` property is set to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`;

After these steps you should run `flutter clean` and try to build again.
