### ISSUE TITLE
Background Permission Option Label

### ISSUE THREAD

**Issue by sunnykinger** [Baseflow/flutter-permission-handler#458]
## 🚀 Feature Requests

Users might have selected a different language on his/her phone and in order to correctly explain to the user the steps for enabling background location on Android 11 or above, there is a `getBackgroundPermissionOptionLabel()` method which will return the correct option label in the user-selected language.

### Contextualize the feature
It is very useful to have this option so that developers do not need to add custom labels for each language.

### Describe the feature
Users might have selected a different language on his/her phone and in order to correctly explain to the user the steps for enabling background location on Android 11 or above, there is a `getBackgroundPermissionOptionLabel()` method which will return the correct option label in the user-selected language.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by JDDV** [comment]
Hi @sunnykinger, after carefull consideration we decided that this is not something we're going to implement in the permission handler plugin. The reason is because this is purely Android specific functionality which doesn't fit that well in the plug in. That being said, it's always something you can add on your own in your application by using a Method Channel. How to do it can be found in [this guide](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab) about how to write custom platform-specific code.

**Comment by sunnykinger** [comment]
Well, Thanks for the response. 
Yes, I have already added this via Method Channel, but I thought maybe it was something that a lot of guys would need so I suggested this enhancement. I agree with you that it is Android-specific functionality. Maybe write about this in ReadMe?
