### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by kw2019ltd** [Baseflow/flutter-permission-handler#468]
The new Dart version with null-safety was just released 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by gabdsg** [comment]
👍🏻

**Comment by fzyzcjy** [comment]
If I make a PR will it be accepted?

**Comment by thegrxp** [comment]
They are working on it 
https://github.com/Baseflow/flutter-permission-handler/issues/464#issuecomment-790413304

**Comment by mvanbeusekom** [comment]
Version 6.0.0 has been released fully supporting null-safety.

**Comment by ESRSOL** [comment]
PS C:\Users\ESR\Downloads\flutter_projects\rentaa> flutter pub upgrade --major-versions
Because no versions of permission_handler_windows match 0.2.1 and no versions of permission_handler_windows match >0.2.1 <0.3.0, permission_handler_windows
  ^0.2.1 is forbidden.
So, because rentaaa_customer_app_flutter depends on permission_handler >=11.3.1 which depends on permission_handler_windows ^0.2.1, version solving failed.      
Failed to update packages.
PS C:\Users\ESR\Downloads\flutter_projects\rentaa> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.96.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
when i pub get then again and again issue all dependencies how to resolving that
