### ISSUE TITLE
Permission.accessMediaLocation always returns PermissionStatus.undetermined on Android 9

### ISSUE THREAD

**Issue by MikeRee** [Baseflow/flutter-permission-handler#472]
## 🐛 Bug Report

I started to prompt users with a list of missing permissions and noticed that on earlier devices, accessMediaLocation always returns "PermissionStatus.undetermined" and then logs this in the console:

D/permissions_handler(17367): No permissions found in manifest for: 18

If you do a Permission.accessMediaLocation.request() it will once again return undetermined and log a no permission found in the console.

### Expected behavior

Would expect to get back a status of either "granted" as in the app will operate as if the permission was granted or "doesNotExist" to let me know that I shouldn't try to prompt the user that this permission is missing.

### Reproduction steps

Permission.accessMediaLocation.request() on Android 9

### Configuration

**Version:** 5.1.0+2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Initially I figured `undetermined` would make the most sense as the permissions didn't exists and therefore we cannot determine its access level. Re-evaluating this I think from a user perspective it would be easier if the permission is indeed returned as `granted` since pre-Android 9 permissions are implicitly granted. 

I will make an update and fix this issue. Thanks for your report.

**Comment by JDDV** [comment]
@MikeRee, PR #499 should fix the problem, so this issue will be closed. If you're still facing this issue please let us know so we can help!
