### ISSUE TITLE
Permission status returns "Permission Denied" even after "Permanently Denied" for android flow

### ISSUE THREAD

**Issue by fldvlpr** [Baseflow/flutter-permission-handler#478]
## 🐛 Bug Report

I was trying to add permission_handler in my project. I've followed documentation. But, when I try to check permission status It gives me permission denied even after I've permanently denied for permission asking dialog.

`PermissionStatus permissionStatus = await permission.status;`

But, above command keep giving me status of **permission.denied** instead of **permission.permanentlyDenied**

Can, you please look in to this issue.

I'm using latest version **"6.0.1+1"** from pub. I'm using flutter stable SDK  Release **"2.0.1"**

Let me know possible solutions.

Thanks.

**Comment by Sreadon** [comment]
I've the problem too. Even though I've permanently denied permissions, "Permission.camera.status" and others still return "PermissionStatus.denied" instead of "PermissionStatus.isPermanentlyDenied". Tested on Samsung GALAXY A41 on Android 10. 

Thanks.

**Comment by fldvlpr** [comment]
@Sreadon Let me know if you find any solution for this issue.

Thanks.

**Comment by Sreadon** [comment]
@fldvlpr I'll try to understand what's wrong tomorrow. Please let me know if you find something. Are we "alone" in this case? I've migrated my app to NullSafety some I'm kind of stuck in there :|

**Comment by interlochen** [comment]
I would just like to add here that I am experiencing this behavior in iOS as well. Currently testing with simulator on iphone 12 pro with iOS 14.4

**Comment by champeauxr** [comment]
This is not necessarily a new 6.0 null safety issue. I'm seeing the same behavior on 5.0.1, but only on Samsung phones (so far anyhow). With 5.0.1, it works correctly on a Pixel 3a (Android 11) and an LG V30 (Android 9), but on a Samsung S20FE (Android 11), `Permission.camera.isPermanentlyDenied` returns `false` after permanently denied. My QA reproduced this on another Samsung phone, but I'm not sure which one.

**Comment by champeauxr** [comment]
FYI... I upgraded to `5.1.0+2` and it now works properly on my Samsung S20 FE.

**Comment by xmany** [comment]
same here, please it needs to be resolved

**Comment by Sreadon** [comment]
So I've taken time to test it fully on my Samsung test phone (Galaxy A41), here are the result:

Fresh install of the app (debug mode): 
* First result = PermissionsStatus.denied 
* Denied permission (not permanently) = PermissionStatus.denied
* Permanently denied permission = PermissionStatus.denied 
* Every other calls after this stays on PermissionStatus.denied instead of PermissionStatus.isPermanentlyDenied

**Comment by mvanbeusekom** [comment]
This is expected behaviour. The Android SDK only allows checking if permissions are granted or denied (there is no option, enum value or other method to determine if the user permanently denied permissions).

In previous versions (pre-6.0.0) we tried to resolve this by persisting a key to the shared-preferences containing the output of the `shouldShowRequestPermissionRationale` method after requesting permissions. If this value returned `false` directly after the user denied permission you could conclude that permission has been denied permanently. This however was never really how Android intended the method to be used and starting from Android API 30 it resulted into a serieus bug when using the "Ask every time" permission.

So we determined to adhere to the Android permission flow and only return the `permanentlyDenied` permission when we are sure permissions are denied permanently. Which is directly after requesting permissions. So the recommended way to handle permissions now would be:

```dart
var status = await Permission.camera.status;
if (status.isDenied) {
  status = await Permission.camera.request();
}

if (status.isPermanentlyDenied) {
  // Handle logic when permissions are permanently denied...
}

if (status.isDenied) {
  // Permissions are denied, you cannot access the camera (you can request permissions again)...
} 

// Permissions are granted, so you can use the camera...
```

**Comment by ruskakimov** [comment]
@mvanbeusekom I believe this should be documented. Probably something like:
> Call `request()` before `isPermanentlyDenied`.
