### ISSUE TITLE
How is this plugin possibly working???

### ISSUE THREAD

**Issue by zuboje** [Baseflow/flutter-permission-handler#481]
## 🐛 Bug Report

There are two issues that are not really explained very well:

1. Import - when the plugin is imported every variable that is a type of a "List<T>" is broken with the error message "_**List isn't a type. Try correcting the name to match an existing type.**_"

2. Usage, if problem number 1 is resolved and there are no lists in a particular class when I attempt to call `await Permission.camera.status`, camera is highlighted in red with error message "**_The getter 'camera' isn't defined for the type 'dynamic Function()'.
Try importing the library that defines 'camera', correcting the name to the name of an existing getter_**"

### Expected behavior

1. When plugin is imported no variables that are a type of a List<T> should be broken.
2. Camera constant for "Permission" class should be recognized instead, it is not.

### Reproduction steps

Setup empty class try creating variable that is List<String>, try calling `var status = await Permission.camera.status;`

### Configuration

**Version:** 5.1.0+2

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@zuboje I am sorry to say but it is not clear to me what your problem is. You are mentioning problems with the `List` type, this doesn't seem related to the permission handler. The `List` type is part of `dart:core` framework and if you have installed Flutter correctly this should simply be available to you. 

Next you mention that the `camera` constant for `Permission` class should be recognised, which if you use the correct import statement this works just fine for me. Just to make sure I have created a small test application and I had no problems at all. Here are the steps I used:

1. Create new Flutter application: `flutter create permission_test`;
2. Open the newly created application in your favourite IDE (in my case Visual Studio Code);
3. Add a dependency to the `permission_handler: ^5.1.0` to your pubspec.yaml;
4. Add the required permissions to the `AndroidManifest.xml` and `Info.plist` files (see [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/android/app/src/main/AndroidManifest.xml) and [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/ios/Runner/Info.plist) for examples). Note that this is also documented in the README.md file under the "Android" and "iOS" sections; 
5. Create a new file called `test.dart` and add the following code:
```dart
import 'package:permission_handler/permission_handler.dart';

class Test {
  Future<PermissionStatus> getCameraPermissionStatus() {
    return Permission.camera.status;
  }
}
```
6. Switch to the `main.dart` file and import `test.dart`: `import 'test.dart;`
7. Next call the `getCameraPermissionStatus()` method from the `_incrementCounter` method in the `main.dart` file and print the result:
```dart
  void _incrementCounter() async {
    final test = Test();
    test
        .getCameraPermissionStatus()
        .then((status) => print('Camera permission: $status'));

    setState(() {
      _counter++;
    });
  }
```

Now if I run the application and hit the floating action button the camera permission status is nicely printed to the console. Also here is a screenshot showing the IDE recognising the camera constant:
<img width="675" alt="Screenshot 2021-03-14 at 15 54 43" src="https://user-images.githubusercontent.com/13098888/111073515-52ffc780-84df-11eb-81f3-a1d544b0cb24.png">

So I really don't know what your problem is, but it sounds like you have something broken in your environment. It definitely works on my machine and the CI is also green (which compiles the example app).

**Comment by hitshydev** [comment]
I experienced the same behavior as @zuboje , but a restart of the IDE fixed the issue. I am using the OSS version of VSCode with the Flutter Extension and FVM. I guess the dart analyzer is the root of the problem here not the permission_handler.
