### ISSUE TITLE
shouldShowRequestRationale always return false after "denied and don't ask again"

### ISSUE THREAD

**Issue by phamconganh** [Baseflow/flutter-permission-handler#496]
## 🐛 Bug Report

shouldShowRequestRationale always return false after "denied and don't ask again"

### Expected behavior

My app requied bluetooth permission.  After user choose "denied and don't ask again", i check and show requied bluetooth permission, but when i check `Permission.bluetooth.shouldShowRequestRationale`, it always return false

**Version:** 6.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@phamconganh that is correct and expected behaviour. The `shouldShowRequestRationale` will only return `true` when the user has denied permissions without selecting the "don't ask again" option (or on Android API 30, only after the first time the user denied the permissions).

What Google is trying to achieve is that you show an additional explanatory message on why your App needs certain permissions, before asking the user for the permissions again (after the user denied them initially). If the user selected the "don't ask again" option the user indicated you should never ask for permissions again and Android will not show the permission dialog if you do request for those particular permissions. In this case the permission_handler plugin will return the `permanentlyDenied` status and you should redirect the user to the App settings to update permissions there.


More details can be found [here](https://developer.android.com/training/permissions/requesting#explain).

**Comment by phamconganh** [comment]
@mvanbeusekom tks for your quickly reply. In this case the `Permission.bluetooth.isPermanentlyDenied` return false too.

**Comment by mvanbeusekom** [comment]
Yes unfortunately Android only returns `granted` or `denied` when checking permissions. We have no option (at the moment) to determine for sure if permissions are just "denied" or "permanently denied" unless we request permissions. So the `Permission.bluetooth.request()` method will be able to return `permanentlyDenied` status if the user selected the "Don't ask again" option. After that the permission handler will store this result in memory so if you use the `Permission.bluetooth.isPermanentlyDenied` check later in your App it will work, but of course the information will be lost once the App is closed and restarted.

**Comment by phamconganh** [comment]
this is my code
```
      final PermissionStatus status = await Permission.bluetooth.request();
      logger?.info('isDenied::: ${status.isDenied}');
      logger?.info('isGranted::: ${status.isGranted}');
      logger?.info('isLimited::: ${status.isLimited}');
      logger?.info('isPermanentlyDenied::: ${status.isPermanentlyDenied}');
      logger?.info('isRestricted::: ${status.isRestricted}');
      logger?.info(
          'shouldShowRequestRationale::: ${await Permission.bluetooth.shouldShowRequestRationale}');
```
and in this case, it print
```
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.392752: isDenied::: false
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.395369: isGranted::: true
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.395938: isLimited::: false
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.396578: isPermanentlyDenied::: false
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.397137: isRestricted::: false
I/flutter (29213): [INFO]: [DeviceScanScreen]: 2021-03-22 17:27:29.405080: shouldShowRequestRationale::: false
```
