### ISSUE TITLE
Some Android phones get incorrect location permissions when they are running部分安卓手机在运行时，获取的定位权限不正确

### ISSUE THREAD

**Issue by jkLennon** [Baseflow/flutter-permission-handler#497]
Some Android phones ask for location and turn it on the first time they boot up.After some time, the App will run in the background. At this time, the location permission is prohibited in the system, and the App will be returned to obtain the previous permission information. The permission_handler plug-in will return  Permission.location.isGranted == true

device：
xiaomi-Android：7.0

code：
permission_handler: ^5.1.0+2

var status = await Permission.location;
if(status.isGranted != true){
  var Permissions = await Permission.location.request();
  if (Permissions.isGranted) {     
    return true;
  } else {        
    return false;
  }
}else{    
  return true;
}

**Comment by mvanbeusekom** [comment]
This is correct and expected behaviour. On pre-Android Q devices you can only request permission to access the location (it doesn't matter if you access it in the background or foreground). When running pre-Android Q and you have listed either the `ACCESS_FINE_LOCATION` or `ACCESS_COARSE_LOCATION` keys in your AndroidManifest.xml and the user granted permission, the App will have permission to access the device's location at anytime (foreground or background). 

Only since Android Q (Android 10 or Android API 29), Google introduced the separate `ACCESS_BACKGROUND_LOCATION` permission which requires App developers to specifically request permission to access the location for cases where the App is running in the background.

Even so the permission_handler is not context aware. It will simply return the status of the permission you are requesting no matter if your app is currently running in the background or not. So it will still return `true` when you check for permission on the `Permission.location.isGranted` since it will simply look in your AndroidManifest.xml if you have listed the `ACCESS_FINE_LOCATION`, `ACCESS_COARSE_LOCATION` or `ACCESS_BACKGROUND_LOCATION` and return if any of these is granted yes or no. 

If you want to specifically check if background permissions are allowed you should use the `Permission.locationAlways.isGranted` permission. In this case it will only test the permissions of the `ACCESS_BACKGROUND_LOCATION` permission and returns `true` if the users allowed accessing the location from the background or `false` if it is not allowed (note that this will only have any value on Android Q and higher).

**Comment by jkLennon** [comment]
@mvanbeusekom 
AndroidManifest.xml：
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"></uses-permission> 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"></uses-permission>
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"></uses-permission>

location.dart:
import 'package:permission_handler/permission_handler.dart';
var test = await Permission.location.serviceStatus.isEnabled;
var status = await Permission.location.isGranted; 
print(test);
print(status);
![image](https://user-images.githubusercontent.com/44989491/112090857-4827ef80-8bcf-11eb-92d9-8714a3eb4911.png)

![image](https://user-images.githubusercontent.com/44989491/112090200-18c4b300-8bce-11eb-8497-544522a2fb16.png)
![image](https://user-images.githubusercontent.com/44989491/112090261-3560eb00-8bce-11eb-9b12-093cc6a2943c.png)

Locations are enabled on thefirst request.After manually disabling location permissions,The system is set to disable positioning and returns true for all states
