### ISSUE TITLE
Should I maintain permission status manually as of version 6.0.0?

### ISSUE THREAD

**Issue by jezsung** [Baseflow/flutter-permission-handler#501]
As of 6.0.0, the permission status `undetermined` has been removed and it defaults to the `denied` status. Because of this, there's no way for us to check if users permanently denied the permission before without calling `request()`. This causes one problem. I couldn't determine when to show dialog to navigate users to app settings when the status is `permanentlyDenied`.  Please see the comment below. It seems like I need to save the status manually to achieve properly permission request flow.

``` dart
Permission permission = Permission.photos;
PermissionStatus permissionStatus = await permission.status;
if (permissionStatus == PermissionStatus.denied) {
  permissionStatus = await permission.request();
  if (permissionStatus == PermissionStatus.permanentlyDenied) {
    // If I try to call openAppSettings() here, it also opens app settings right after users permanently denied. 
    // It only calls openAppSettings() when the users are trying to request permission second time.
    return;
  } 

  if (permissionStatus == PermissionStatus.denied) {
    return;
  }
}
```

**Comment by mvanbeusekom** [comment]
Hi @jezsung, storing the permissions will get you into problems with the new `Ask every time` option introduced in Android API 30. The problem is that if the user updates permissions outside the App (via the App Settings) to "Ask every time" the next time you will check permission Android will return `denied` (as Android will only return `granted` or `denied`).

So assume the user permanently denied and you have saved this to e.g. shared preferences. While working with your App the user decides to allow permissions and exits your App to navigate to the App Settings and updates the permissions to "Ask every time". When the user restarts your App, you will check permissions and it will return `PermissionStatus.denied` (default Android flow, the user has not explicitly granted permissions so it will implicitly assume permissions are denied). Next you check the settings you previously saved and it will return that permissions where permanently denied. If you follow your stored settings you shouldn't request permissions, while actually you are allowed to request permissions and the user is likely to grant them this time.

This is the whole reason we stopped storing permissions. I think the following flow would be ideal:

```dart
Permission permission = Permission.photos;
PermissionStatus permissionStatus = await permission.status;
if (permissionStatus == PermissionStatus.denied) {
  permissionStatus = await permission.request();
  if (permissionStatus == PermissionStatus.permanentlyDenied) {
    // Show the user a message explaining why your App needs the requested permissions
    // and which functionality doesn't work. Here you can include a link or button that will
    // call the `openAppSettings` when pressed.  
    return;
  } 

  if (permissionStatus == PermissionStatus.denied) {
    // Show the user a message explaining why your App needs the requested permissions
    // and which functionality doesn't work. Here you can include a link or button that will
    // request permissions once again and the user can grant permissions this time around.  
    return;
  }
}
```

More detailed explanation of the above reasoning can be found [here](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0#android-permission-update).

I hope this is clear, of course if I missed something in my logic please let me know I would be happy to discuss it.
