### ISSUE TITLE
Keep current screen when requesting permission

### ISSUE THREAD

**Issue by andzejsw** [Baseflow/flutter-permission-handler#507]
How to keep current screen, when requesting permission!?
When I call "Permission.location.request()", screens are changed and permission is requested in different screen. How can i keep current one?

**Comment by andzejsw** [comment]
Sorry. I am redirected to Main screen immediately after permission request. But yes, it is on Abdroid. My code:
```
    bool hasPermission = await Permission.location.isGranted;
    if (!hasPermission) {
      bool granted = await Permission.location.request().isGranted;
      if(granted) {
        // Some code here
      }
    }
```

**Comment by JDDV** [comment]
Hi @andzejsw, I still can't seem to reproduce the problem, for me it is working just fine.
I would like some more information to figure out what the problem is, if possible I would like to see:

- `flutter doctor -v` output
- Android device and Android version you test it on
- Plugin version of the permission handler you use

I started a new project (the standard incremental counter flutter project) and add the permission handler to the pubspec.yaml.
In the _incrementCounter() method I've put your code you provided in there, so the method will looked like:

```
void _incrementCounter() async {

    bool hasPermission = await Permission.location.isGranted;
    if (!hasPermission) {
      granted = await Permission.location.request().isGranted;
      if(granted) {
        print('hasPermission: $hasPermission & Granted: $granted');
      }
    }
    print('hasPermission: $hasPermission & Granted: $granted');

    //Standard code in the _incrementCounter() method
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
```

This is how I tested the behaviour, and for me it worked as it should, maybe you can test the same thing so we can rule out some things. Let me know!
