### ISSUE TITLE
Calling request() to get the status even not actually requesting permission triggers AppLifecycleState.inactive

### ISSUE THREAD

**Issue by OliverRhyme** [Baseflow/flutter-permission-handler#535]
### Expected behavior
Calling `request()` should not trigger the `ApplifecycleState.inactive` and back again to `AppLifecycleState.resumed` if it does not actually request permission but only gets the status (i.e already granted). This breaks apps that rely on AppLifecycleState to request permission when the user goes back to the app.

### Reproduction steps
call Permission.camera.request(); within a state with `WidgetsBindingObserver` mixin.

**Version:** 7.0.0

**Platform:** 
 :robot: Android

**Comment by JDDV** [comment]
Hi @OliverRhyme, I tried to reproduce this behaviour but I can't seem to get the same results.

Steps I took te reproduce:

- Set up:

Tested on a Samsung S20 on Android 11

- Code:
1. Created a new project and used the standard flutter (the incremental counter)
2. Added the `permission_handler: ^7.1.0` line in the pubspec.yaml and did `pub get`
3. Added `with WidgetsBindingObserver` (`class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver`)
4. Implemented methods for the WidgetsBindingObserver (`initState`, `dispose`, `didChangeAppLifecycleState`)
5. In the incrementCounter() method I ask for permission using `Permission.camera.request()` 
6. I use print(_notification) in the didChangeAppLifeCycleState method to check the state of the AppLifeCycle when it changes

The outcome is that the first time (when the permission isn't allowed yet) that the notification asks for allowing or denying the permission, which will turn the state of the app to `AppLifecycleState.inactive` and after allowing the permission it turns back to `AppLifecycleState.resumed`. The next time I increment the counter in the standard project app it will try to ask again for the permission (since it will go through the same `Permission.camera.request()` code). However, the state of the AppLifeCycle doesn't change for me.

Are the steps I took to reproduce the right steps? if not, can you provide a code snippet?

<details>
<summary>Flutter doctor -v</summary
[√] Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.19041.867], locale nl-NL)
    • Flutter version 2.0.0 at C:\Baseflow\flutter
    • Framework revision 60bd88df91 (9 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Jan-Derk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • SM G780F (mobile) • RZ8R10RN1NF • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
</details>

**Comment by OliverRhyme** [comment]
> Permission.camera.request()

My bad, it should be when you deny it (permanently where it does not show a dialog),  then it would call inactive and resume imediately.

**Comment by JDDV** [comment]
Hi @OliverRhyme, I was able to reproduce what you meant. The reason that the AppLifeCycleState changes is because when you ask for a permission, whether it's `granted` or `denied`, Android has to do some sort of check to see what status the permission has.
The documentation can be found [here](https://developer.android.com/reference/androidx/core/app/ActivityCompat#requestPermissions(android.app.Activity,%20java.lang.String[],%20int))

Here's a small piece of the documentation stating the following:

```This method may start an activity allowing the user to choose which permissions to grant and which to reject. Hence, you should be prepared that your activity may be paused and resumed. Further, granting some permissions may require a restart of you application. In such a case, the system will recreate the activity stack before delivering the result to your ActivityCompat.OnRequestPermissionsResultCallback.onRequestPermissionsResult(int, String[], int[]).```

That being said, you can prevent this behaviour in your program by checking before doing the request() to see what the status is for the permission. The code will look something like this:

```
// Declaration
PermissionStatus ps = PermissionStatus.denied;

//Implementation
if (ps != PermissionStatus.permanentlyDenied){
     ps = await Permission.camera.request();
   }
```

Please let me know if this helped you so the issue can be closed

**Comment by OliverRhyme** [comment]
> Hi @OliverRhyme, I was able to reproduce what you meant. The reason that the AppLifeCycleState changes is because when you ask for a permission, whether it's `granted` or `denied`, Android has to do some sort of check to see what status the permission has.
> The documentation can be found [here](https://developer.android.com/reference/androidx/core/app/ActivityCompat#requestPermissions(android.app.Activity,%20java.lang.String[],%20int))
> 
> Here's a small piece of the documentation stating the following:
> 
> ```This method may start an activity allowing the user to choose which permissions to grant and which to reject. Hence, you should be prepared that your activity may be paused and resumed. Further, granting some permissions may require a restart of you application. In such a case, the system will recreate the activity stack before delivering the result to your ActivityCompat.OnRequestPermissionsResultCallback.onRequestPermissionsResult(int, String[], int[]).```
> 
> That being said, you can prevent this behaviour in your program by checking before doing the request() to see what the status is for the permission. The code will look something like this:
> 
> ```
> // Declaration
> PermissionStatus ps = PermissionStatus.denied;
> 
> //Implementation
> if (ps != PermissionStatus.permanentlyDenied){
>      ps = await Permission.camera.request();
>    }
> ```
> 
> Please let me know if this helped you so the issue can be closed
Hi,

Thank you for the fast response.

I've tried to implement that check, but sadly I cannot know if it is permanently denied without calling the request() function. Thus creating a loop. (I have a callback where when the user returns (AppLifecycleState.resumed) it checks for permission and show camera or message appropriately)

**Comment by JDDV** [comment]
Hi @OliverRhyme, the declaration of the `PermissionStatus ps = PermissionStatus.denied` is a global variable.

In the function where I do this check:
```
if (ps != PermissionStatus.permanentlyDenied){
     ps = await Permission.camera.request();
     print(ps.toString());
   }
```

I also set the global variable `ps` to the last received `PermissionStatus` in that if statement.
the outcome is like this:

First time asking permission, and the pop-up shows up which I deny:
```
I/flutter ( 5922): AppLifecycleState.inactive
I/flutter ( 5922): PermissionStatus.denied
I/flutter ( 5922): AppLifecycleState.resumed
```
The global variable `ps` is set to PermissionStatus.denied


Second time asking permission, and the pop-up shows up which I deny again:
```
I/flutter ( 5922): AppLifecycleState.inactive
I/flutter ( 5922): PermissionStatus.permanentlyDenied
I/flutter ( 5922): AppLifecycleState.resumed
```
The global variable `ps` is set to `PermissionStatus.permanentlyDenied`

The third time **trying** to ask for the permission there is no output due to the `if-statement` being false.

> but sadly I cannot know if it is permanently denied without calling the request() function.

So if I understand correctly, it's not possible to build the `if-statement` check where you call the request() function?

**Comment by OliverRhyme** [comment]
> Hi @OliverRhyme, the declaration of the `PermissionStatus ps = PermissionStatus.denied` is a global variable.
> 
> In the function where I do this check:
> 
> ```
> if (ps != PermissionStatus.permanentlyDenied){
>      ps = await Permission.camera.request();
>      print(ps.toString());
>    }
> ```
> 
> I also set the global variable `ps` to the last received `PermissionStatus` in that if statement.
> the outcome is like this:
> 
> First time asking permission, and the pop-up shows up which I deny:
> 
> ```
> I/flutter ( 5922): AppLifecycleState.inactive
> I/flutter ( 5922): PermissionStatus.denied
> I/flutter ( 5922): AppLifecycleState.resumed
> ```
> 
> The global variable `ps` is set to PermissionStatus.denied
> 
> Second time asking permission, and the pop-up shows up which I deny again:
> 
> ```
> I/flutter ( 5922): AppLifecycleState.inactive
> I/flutter ( 5922): PermissionStatus.permanentlyDenied
> I/flutter ( 5922): AppLifecycleState.resumed
> ```
> 
> The global variable `ps` is set to `PermissionStatus.permanentlyDenied`
> 
> The third time **trying** to ask for the permission there is no output due to the `if-statement` being false.
> 
> > but sadly I cannot know if it is permanently denied without calling the request() function.
> 
> So if I understand correctly, it's not possible to build the `if-statement` check where you call the request() function? If not, than I'm afraid I cannot help you further.

My code requests permission, when AppLifecycle is resumed. So when requesting, it basically causes recursion because resume calls the request permission method (which then starts the camera if granted).

**Comment by JDDV** [comment]
I'm afraid that's an Android issue we are not able to fix as mentioned before. As soon as the call happens (ActivityCompat.requestPermissions) Android changes the LifeCycle whether the permission is already granted, denied, or permanentlyDenied.
