### ISSUE TITLE
Permanently deleted is always false {Android}

### ISSUE THREAD

**Issue by marcodecarolisidt** [Baseflow/flutter-permission-handler#546]
## 🐛 Bug Report
When I tap on "Deny & don't ask again" the next time the permission status is always "denied" and not "permanentlyDenied"

### Reproduction steps
- Ask for permission (any kind)
- Tap on Deny
- Ask the permission again
- Tap on Deny & don't ask again
- Ask for permission again

### Expected result
The Permission status will be "permanentlyDenied"

### Actual result
The Permission status is "deleted"

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by JDDV** [comment]
Hi @marcodecarolisidt, I can't reproduce the error, also I wonder what you mean with Permission status 'deleted' since deleted isn't a possible permission status.

How I tried to reproduce the error:

First try to reproduce was on an Android API 30 (Android 11) device, using the following steps:

1. Used the example app provided by the permission-handler plugin
2. Clicked on camera permission
3. denied permission - Status was `denied`
4. Clicked again on camera permission
5. denied permission - Status was `permanentlyDenied`

Denying twice will result in `permanentlyDenied` on Android 11. So this behaviour is as expected

Second try on Android API 27 (Android 8.1 Oreo), using the following steps:

1. Used the example app provided by the permission-handler plugin
2. Clicked on camera permission
3. denied permission - Status was `denied`
4. Clicked again on camera permission
5. denied permission (did not click on the 'Don't ask again' button - Status was still `denied`
(So this behaviour is different from Android API 30, denying twice does not mean it will be `permanentlyDenied`)
6. Clicked again on camera permission
7. Clicked on 'Don't ask again' and clicked 'Deny' on the pop-up
8. Permission status changed to `permanentlyDenied`

This is also the correct behaviour of the plugin, so I can't seem to reproduce the error.

Can you provide me more information? I would like to see

- Output of the `flutter doctor -v` command
- Device you were testing on (and Android version)
- Version of the plugin you used in the `pubspec.yaml` (if you're not using version ^7.1.0 yet, can you try that first, see if that will fix your problem?)
- Code snippet of the code you're using where you ask and check for the permission

I hoped this helped you, let me know if it helped you, or if you're still stuck on the problem. Thanks in advance!

**Comment by mvanbeusekom** [comment]
Also keep in mind that the `checkPermission` method is no longer able to return `permanentlyDenied` on Android (due to changes in Android API 30). 

The `checkPermission` method is only able to return `denied`, `always` or `whenInUse`. For a more detailed explanation please checkout our wiki page: https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0#breaking-changes
