### ISSUE TITLE
When choose Permission "Deny And Don't Ask Again" Then Permission Status Came isDenied

### ISSUE THREAD

**Issue by rahulrkhot** [Baseflow/flutter-permission-handler#567]
## 🐛 Bug Report

When choose Permission "Deny And Don't Ask Again" Then Permission Status Came isDenied but need to isPermanentlyDenied

Device : Poco X3  (Android V10)
version : permission_handler 8.0.0+2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@rahulrkhot thank you for submitting an issue. 

When, on Android, you check the permissions using `Permissions.camera.status` the only supported status information is either `PermissionStatus.granted` or `PermissionStatus.denied`. 

Since version 6.0.0 the `PermissionStatus.permanentlyDenied` is only supported as direct response on the `Permissions.camera.request()` method. This has been changed due to new restrictions on Android API 30. More details can be found in our [Wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0). 

Hope this answers your question. I will close the issue for now but feel free to leave a comment if you require further information.
