### ISSUE TITLE
isUndetermined Alternative

### ISSUE THREAD

**Issue by Jayvd** [Baseflow/flutter-permission-handler#572]
Previously, we have both isUndetermined status to determine if the user has decided before or not.

But now we only have isDenied status, so how do we know if the user has denied it before? Because in iOS once denied, we need to tell the user to go to Settings to enable the permission.

How do we accomplish this without the isUndetermined status?

**Comment by mvanbeusekom** [comment]
@b-cancel is correct since version 6.0.0 we changed the behaviour of the permissions to accommodate the new requirements on Android API 30 (see our "[Changes in 6.0.0](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0)" wiki article for more details). Both Android and iOS will treat the `PermissionStatus.denied` and `PermissionStatus.permanentlyDenied` in the following way:

- `PermissionStatus.denied` means permissions are unknown or denied but you can try again;
- `PermissionStatus.permanentlyDenied` means permissions have been denied and the user should grant permissions through the OS "Settings" (permissions dialogs will not be shown when requesting permission).

@b-cancel is also correct that we missed this in the documentation and we are working to correct this mistake.

**Comment by Jayvd** [comment]
Thank you @b-cancel @mvanbeusekom Does this mean that now we can use the same code for both iOS and Android like so?

```

    var contactPermissionStatus = await Permission.contacts.status;

    if(contactPermissionStatus.isDenied) {

    }
    else if(contactPermissionStatus.isPermanentlyDenied) {

    }
    else if(contactPermissionStatus.isGranted) {

    }
```

**Comment by b-cancel** [comment]
@Jayvd there are other edge cases to cover, you can see them by exploring the documentation
but since I literally just handled this myself yesterday, here is the code I'm using

`
const Duration normalHumanReactionTime = Duration(milliseconds: 250);

//on Android: if you just deny
//the pop up can come up again and again
//the status continues to be "denied"

//on iOS: if you just deny
//the pop up can't come up again and again
//the status becomes "permanently denied"

//can Contiue on 1. Granted or 2. Limited (for photos and photo albums on iOS14+)
enum NextAction {
  Continue,
  EditManually,
  ExplainRestriction,
  TryAgainLater,
  Error
}

/// Actions that can be executed on a permission.
extension PermissionActions on Permission {
  /// Request the user for access to this [Permission], if access hasn't already
  /// been grant access before.
  ///
  /// Returns the new [PermissionStatus].
  /// or null if PermissionStatus should essentially be unknown
  Future<PermissionStatus> requestWithNull() async {
    final permissionStatus = (await [this].request())[this];
    return permissionStatus;
  }
}

//after trying, focus on the next action
Future<NextAction> tryToGetPermission(
  Permission permission,
) async {
  //grab date time here for a work around an error with the plugin
  DateTime timeBeforeRequest = DateTime.now();

  //I can't just check the status here because it does not yield the most accurate result
  PermissionStatus actualStatus = await permission.requestWithNull();
  DateTime timeAfterRequest = DateTime.now();
  //I also grab the status just to prove my point
  PermissionStatus retreivableStatus = await permission.status;
  //and I grab the request rationale to attemp to find a pattern
  bool shouldShowRequestRationale = await permission.shouldShowRequestRationale;

  //prints in the attempts to catch variable patterns to better predict the behavior
  print(
      "shouldShowRequestRationale? : " + shouldShowRequestRationale.toString());
  print("retreivable: " +
      retreivableStatus.toString() +
      " VS actual: " +
      (actualStatus != null ? actualStatus.toString() : "Unknown"));

  //!this shouldn't happen but I know that it does
  //when we permanently deny in android...
  //0. immediately after the status will be "permanently denied"
  //1. but afterwards the retreived status will be "denied"
  //2. until I request that status again and get "permanently denied"
  //* I have no 100% reliable way to check if "denied" became "permanently denied" because
  //a. the pop up came up and the user converted it
  //b. the error "converted" it
  //* but I can check the difference between the date times above to be able to tell
  //* somewhat reliably whether the pop up came up (CASE A) or whether it didn't (CASE B)
  if (retreivableStatus != actualStatus) {
    print("+\n+\n+ERROR+\n+\n+");
  }

  //I needed the null status for some checks above
  //but I didn't change anything below, so I revert back to it's default behavior
  if (actualStatus == null) {
    actualStatus = PermissionStatus.denied;
  }

  //to handle edge case that print ERROR above
  Duration timeBetweenRequestAndReturnedStatus =
      timeAfterRequest.difference(timeBeforeRequest);
  //for testing
  print("time betweeen request and the returned status: " +
      timeBetweenRequestAndReturnedStatus.toString());
  //! the error seems to "complete the request" in (110 -> 160) ms
  //! normalHumanReactionTime (250ms) might be cutting it close,
  //! the fastest I ever was to perform the action was 500ms
  //handles the edge case
  bool popUpCameUp =
      timeBetweenRequestAndReturnedStatus > normalHumanReactionTime;

  //NOTE: is Limited as of June 2nd 2021 only relates to photos and photo albums on iOS14+
  if (actualStatus.isGranted || actualStatus.isLimited) {
    return NextAction.Continue;
  } else if (actualStatus.isDenied) {
    return NextAction.TryAgainLater;
  } else {
    //! although the plugin says that "permanently denied" is only for android
    //it also comes up whenever a user denies a permission within iOS
    if (actualStatus.isPermanentlyDenied) {
      if (popUpCameUp) {
        return NextAction.TryAgainLater;
      } else {
        return NextAction.EditManually;
      }
    } else {
      //edge cases are different per platform
      if (Platform.isAndroid) {
        return NextAction.Error;
      } else if (Platform.isIOS) {
        if (actualStatus.isRestricted) {
          // restricted(only iOS [OS won't allow it])
          return NextAction.ExplainRestriction;
        } else {
          return NextAction.Error;
        }
      }
    }
  }
}`
