### ISSUE TITLE
[iOS] - Bluetooth request returns denied for first time installation

### ISSUE THREAD

**Issue by jlubeck** [Baseflow/flutter-permission-handler#585]
## 🐛 Bug Report

Just running this simple snippet returns `PermissionStatus.denied` on a freshly installed device:
```dart
      final bluetoothPermissionStatus = await Permission.bluetooth.request();
```

Also, when going to the phone settings, the App doesn't even show up in the list, so doesn't look like it's registering the app to be using this permission. 

### Expected behavior

I was expecting to get the dialog requesting permission and wait to get the proper response. 

### Reproduction steps

Use   `permission_handler: ^8.0.1`
Have proper keys on Plist: 
```xml
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>uses Bluetooth to connect to your devices.</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>uses Bluetooth to connect to your devices.</string>
```
Uncomment permission on `Podfile`
```ruby
          ## dart: PermissionGroup.bluetooth
          'PERMISSION_BLUETOOTH=1',
```

### Configuration

**Version:** 8.0.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Sheetal-25** [comment]
I'm having the same issue with LocationAlways and Bluetooth permission in both the platform (📱 iOS
 🤖 Android) have you found any solution? @jlubeck

**Comment by henlamk** [comment]
Having the same issue with camera and microphone.

**Comment by sarinupreti** [comment]
+1 for locationAlways

**Comment by mvanbeusekom** [comment]
Hi @jlubeck, 

Thank you for raising this issue. Bluetooth permissions on iOS are a bit different then other permissions supported by the permission_handler plugin. The issue here is that Apple doesn't provide an API explicitly request bluetooth permissions, instead iOS will implicitly request the required bluetooth permissions when the bluetooth API is accessed. 

Apple will only allow third-party developers to check the current permissions (i.e. are permissions currently granted or denied). Since (by popular demand) we did want to add some sort of support to handle bluetooth permissions (especially for the Android side) we decided to implement the check for permissions on iOS aswel. So if you want to know the current permission state on iOS you can run `await Permission.bluetooth.status()`. But since the permission_handler API also requires an implementation for the `request()` method we decided to return current status here also. 

We are aware that the documentation needs some improvements on this and we will expand on this in the near future. So in short Apple doesn't allow us to explicitly request bluetooth permissions and therefore the permission_handler will return the current permission status when executing `await Permission.bluetooth.request()`. 

@Sheetal-25, @henlamk and @sarinupreti, for all other permissions explicitly requesting permissions on iOS should work. Please make sure you enabled the permissions in your `ios/Podfile` file and added the necessary configuration to the `ios/Runner/Info.plist` file as documented in the "iOS" section of our [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) file. 

>Note: take special attention to the fact that we flipped the configuration in your `ios/Podfile` since version 8.0.0 of the plugin. Pre version 8.0.0 all permissions were enabled by default and you had to configure the permissions you didn't want to use. Since version 8.0.0 you will have to explicitly "enable" permissions you want to use.

If you continue to have problems please create a new issue mentioning the:

1. Version of the plugin you are using;
2. Contents of your `ios/Podfile` and `ios/Runner/Info.plist` files;
3. Code snippet on how you use the plugin (preferably a complete reproduction example);
4. The output of the `flutter doctor -v` command.

**Comment by jlubeck** [comment]
Hey @mvanbeusekom thank you for your thorough reply. It makes sense with what I'm seeing and I'll see how to go around it. 

On another note, couldn't you just start scanning for bluetooth devices when we run `request()` ?

**Comment by mvanbeusekom** [comment]
@jlubeck that seems like possible solution, we will investigate it further. For now I will create a new issue to track the progress on this enhancement. Thank you for the feedback.
