### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by define111** [Baseflow/flutter-permission-handler#603]
## 🚀 Feature Requests

Is it planned to support the flutter web?

### Platforms affected (mark all that apply)
- [x] :web

**Comment by rgb1380** [comment]
Please respond to this question. This is a must have plug-in for Flutter and will be good to know if web support is planned or not. Thanks.

**Comment by johnwcchau** [comment]
for your reference i got my own implementation here https://github.com/johnwcchau/permission_handler_web

**Comment by loic-hamdi** [comment]
Any update?

**Comment by aytunch** [comment]
Hi, sorry to bother again but is Web support under your radar? Or can you recommend alternatives?

**Comment by JeroenWeener** [comment]
Web support is not currently on our radar, mostly because the requirements for web differ substantially from the mobile platforms. That does not mean we do not welcome PRs that aim to add web support, however. On the contrary! If you wish to see web support for the plugin please feel free to open a PR or reach out. We'd be happy to offer support.
