### ISSUE TITLE
Permission.storage gives only access to ACESS MEDIA ONLY in android 11 can't write to exteranal storage

### ISSUE THREAD

**Issue by vaibhavpallod** [Baseflow/flutter-permission-handler#606]
### Expected behavior
ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION should be allowed.
### Reproduction steps
https://stackoverflow.com/questions/68141021/cant-we-make-folder-programatically-in-external-storage-of-android-r-i-e-and

### Configuration

**Version:** 8.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Hi @vaibhavpallod, I read the StackOverflow link you posted here. It worked on Android 10, but not on Android 11 you said. Have you tried using the `manageExternalStorage` permission? In the manifest you should add this:

```
 <!-- Permissions options for the `manage external storage` group -->
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

```
And of course you need to request() the permission.

Please read the documentation of the manage external storage, because Google needs to approve the usage of the `manageExternalStorage`. Let me know if this fixed your problem!
