### ISSUE TITLE
why don't we see the ios app setting page anymore?

### ISSUE THREAD

**Issue by moesaid** [Baseflow/flutter-permission-handler#618]
So I am using flutter-permission-handler to handle all the permission functionality,

for E.G

```
  // Location Permission
  askForLocation() async {
    // Permission type
    var status = await Permission.location.request();

    if (status.isGranted) {
      _location.value = status.isGranted;
      update();
    } else {
      print('open setting');
      openAppSettings();
    }
  }
```

work as expected on android but when it comes to ios it always returns **permanently denied** 

however, with that kind of return it should open the app setting page, it opens only the home setting page on the simulator and a physical device.

my first response was to try to get the app from the setting page I couldn't find the app itself. 

you can see the behaviour in this video 
https://youtu.be/ugpFMFyKhLY

anyone facing the same issue?

**Comment by mvanbeusekom** [comment]
@moesaid you have most likely upgraded to version 8.0.0 (or higher) and missed the breaking iOS change (see [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#800)).

Since version 8.0.0, on iOS, permissions are disabled by default. Which mean the logic of checking and requesting these permissions are not included in the final binary and the implementation will always return `PermissionStatus.permanentlyDenied`.  This has two big advantages:

1. Apple will not complain when you submit the App that your App is accessing certain SDK elements for which you need to list records in your `Info.plist` (and in some cases even then Apple would reject your App because you never really show these permissions). Of course you could already work around this by explicitly disabling permissions in your Podfile;
2. We don't have to introduce a breaking change each time we add support for new permissions to the plugin. In version 7 and below this was a problem because with the introduction of a new permission people need to disable it in their Podfile or risk Apple rejecting their App.

So what you probably need to do is add some configuration to your Podfile which enables the permissions your App needs. Instructions are documented in detail in the "iOS" section of our [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/30939b0a4759d8120ecce155e781964443ea258f/permission_handler/README.md).

I am going to close this issue now, but feel free to leave a comment if you need further assistance.
