### ISSUE TITLE
incompatibility with flutter_facebook_login google_sign_in

### ISSUE THREAD

**Issue by angelcgdev** [Baseflow/flutter-permission-handler#623]
## 🐛 Bug Report

    when adding the dependencies
        flutter_facebook_login: ^ 3.0.0
        google_sign_in: ^ 5.0.4
    
    I get in the console
    
    
    E/flutter (27841): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
    E/flutter (27841): #0      MethodChannel._invokeMethod
    package:flutter/…/services/platform_channel.dart:156
    E/flutter (27841): <asynchronous suspension>
    E/flutter (27841): #1      MethodChannelPermissionHandler.checkPermissionStatus
    package:permission_handler_platform_interface/…/method_channel/method_channel_permission_handler.dart:15
    E/flutter (27841): <asynchronous suspension>
    E/flutter (27841): #2      FuturePermissionStatusGetters.isGranted
    package:permission_handler_platform_interface/src/permission_status.dart:80
    E/flutter (27841): <asynchronous suspension>
    E/flutter (27841): #3      _SplashScreenState.loading
    package:/…/shared/splashScreen.page.dart:56

### Expected behavior
    a permission query without problems as it usually used to be

### Configuration
    using
    Flutter 2.0.0
    Dart 2.12.0

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

an apology for english, i'm not a native speaker.

**Comment by JeroenWeener** [comment]
Hi @angelcgdev, thank you for reaching out!

First of all I want to apologize for us not getting back to you. The good news: we have shifted priorities heavily towards maintaining the plugins again. Since this issue has been open for more than two years, I am going to close it. If you still encounter this issue, or any other issue with the permission handler plugin, feel free to open a [new ticket](https://github.com/Baseflow/flutter-permission-handler/issues/new/choose).
