### ISSUE TITLE
request() does not ask for the location dialog in IOS

### ISSUE THREAD

**Issue by BasitCh** [Baseflow/flutter-permission-handler#634]
the request() function does not ask for the location permission dialog it returns denied always. while switching back to 7.2.0 it works fine on the IOS.

**Version:** 8.1.4

**Platform:** 
- [ ] :iphone: iOS

**Comment by JDDV** [comment]
@BasitCh have you updated the podfile? Since version ^8.0.0 the podfile should look different than it did before as stated in the [setup section](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) of the documentation.

your podfile should say something like:

```
## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
```

Can you also try to run a flutter clean followed by a flutter pub get and pod install to make sure no caching issues will happen?

also make sure you read the documentation stated when using `locationAlways`. The user should first ask for `locationWhenInUse` and then the you can request the `locationAlways` permission.

Let me know this solved your problem!

**Comment by BasitCh** [comment]
yeah by adding that in podfile it asks for dialog now. but if i have given the always allow permission and using this code every time to get location 
  PermissionStatus permissionStatus = await Permission.location.request();
        if (permissionStatus.isGranted) {
          Location newLocation = await getCurrentLocation(
              isPlayServicesEnable: Platform.isAndroid &&
                  googlePlayServicesAvailability ==
                      GooglePlayServicesAvailability.success);
}
then it gets crash, for that purpose i need to add this check i guess
if (await Permission.locationWhenInUse.serviceStatus.isEnabled) {
  // Use location.
}

**Comment by JDDV** [comment]
The new error you have sounds like it can be related to issue #633, we're looking into that one now currently and I'll keep you up to date!

**Comment by JDDV** [comment]
Hi @BasitCh, a new version is released of the permission handler plugin (version ^8.1.4+1). This should solve your problem most likely. can you test if this solves your problem and let me know so I can close this issue if it works? 
Thanks in advance!

**Comment by BasitCh** [comment]
@JDDV Thanks for the update it does not crash now, but there is one question 
if i add this check before requesting the permission like this
  if (await Permission.locationWhenInUse.serviceStatus.isEnabled) {
      // move to Home page
      moveToHomePage();
    } else {
      PermissionStatus permissionStatus = await Permission.location.request();
      if (permissionStatus.isGranted) {
        moveToHomePage();
      } else {
        Future.delayed(const Duration(seconds: 2), () {
          moveToManualLocationPage();
        });
      }
    }

and if i re-install the application then it does not ask for the permission it always goes to the if() condition and perform its operation why this is happening before this i was directly calling the request function to request and check for the permission.

**Comment by JDDV** [comment]
Hi @BasitCh,

Your code snippet, as mentioned above here, will always go to the `moveToHomePage()` method as long as you have the `Location Services` in your iPhone settings on. This happens because you check for the `serviceStatus` of the `locationWhenInUse` permission. the serviceStatus will check the phone settings about the status of the service. So for location service status the OS will look if the setting is `on` or `off` for the `Location Service` (see image below).

<img width="396" alt="Schermafbeelding 2021-08-05 om 10 00 41" src="https://user-images.githubusercontent.com/47666699/128314032-74a023af-079d-4e1b-834f-8c13e757a8e0.png">

So in this image, the first if-statement (```if (await Permission.locationWhenInUse.serviceStatus.isEnabled) {
// move to Home page
moveToHomePage();
}```) will always be true.

This will happen every time, also when you re-install the app, since the OS will check the status of that Location Service slider when asking for the `serviceStatus`.

If the slide is off, your code would go in the else-statement (executing this line: ```PermissionStatus permissionStatus = await Permission.location.request();```) which will return a `PermissionStatus.PermanentlyDenied` which makes sense since you denied the 'Location Service'. So the code you wrote it probably not entirely correct.

I think this is what you would like to achieve:

```
if (await Permission.locationWhenInUse.serviceStatus.isDisabled {
      // If the slider for the Location Service in the settings screen is OFF (disabled), guide the user to the settings screen.
      openAppSettings();
    } else {
      // Request the permission for the Location permission
      PermissionStatus permissionStatus = await Permission.location.request();
      if (permissionStatus.isGranted) {
        moveToHomePage();
      } else {
        Future.delayed(const Duration(seconds: 2), () {
          moveToManualLocationPage();
        });
      }
    }
```

One small remark, you check the `serviceStatus` for the `locationWhenInUse` permission, but request the `location` permission. Maybe it's better to check the serviceStatus and ask the permission for the same permission since it will look/read cleaner. But the code will act the same way either way.

Let me know if this helped you out!
