### ISSUE TITLE
FileSystemException: Directory listing failed, path = './' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by walikhan226** [Baseflow/flutter-permission-handler#645]

**Comment by JDDV** [comment]
Hi @walikhan226, I can not help you without any information.
Can you please send me a clear description of your problem, a code snippet of your code which introduces this error, and a `flutter doctor -v` output.

**Comment by kamlesh9070** [comment]
@walikhan226 You need to specifiy targetSdkVersion **30** in build.gradle

**Comment by moovida** [comment]
Dear @JDDV , I might be able to supply more information to this, since I am fighting probably the same issue.

Just as a context,  I am trying to continue using legacy storage support by adding: 
```
android:requestLegacyExternalStorage="true"
```
to the manifest.

Also I am keeping target sdk to 29 as advised by android devel channels and compile sdk to 30 as requested by the plugin:

```
        minSdkVersion 21
        targetSdkVersion 29
        compileSdkVersion 30
        buildToolsVersion = "29.0.2"
```

Storage permissions are properly asked and allowed at app startup. I also checked in debug mode and storage is granted.

But then (on Android 11), as soon as it tries to open an existing sqlite db for writing, the app breaks due to a readonly issue. It seems like it is ignoring the requestLegacyExternalStorage setting.
