### ISSUE TITLE
Reason Message

### ISSUE THREAD

**Issue by didifend** [Baseflow/flutter-permission-handler#646]
## 🚀 Feature Requests

Permission Request Message
![Screenshot_4](https://user-images.githubusercontent.com/39362311/127789948-5b001500-c943-409e-854b-34d9f7ea1a5f.jpg)

### Contextualize the feature
in a new rules of Google Play want to know specific reason for permission use

### Describe the feature
I want to show Reason Message space in Permission Request,  Why we must allow this permission. Especially for Contact Permission. 

### Platforms affected (mark all that apply)
- [ V] :iphone: iOS
- [ V] :robot: Android

**Comment by JDDV** [comment]
Hi @didifend, thank you for your suggestion.
For iOS this is easily fixed by adding the message you want to show in the `plist.info`.

For example for the microphone permission:

```
<!-- Permission options for the `microphone` group -->
    <key>NSMicrophoneUsageDescription</key>
    <string>The app needs permission for the microphone so we can record your voice for the app.</string>
```

For Android it's a bit harder, the documentation of Android does say this:
```
The permissions dialog shown by the system when you call requestPermissions() says what permission your app wants, but doesn't say why. In some cases, the user may find that puzzling. It's a good idea to explain to the user why your app wants the permissions before calling requestPermissions().
```

The solution for this is to tell the user before requesting the permission in some way. but it's not possible to have a message in the permission request dialog as shown in your picture.
