### ISSUE TITLE
Permission.requestInstallPackages.request() 申请后 闪退

### ISSUE THREAD

**Issue by nayoTT** [Baseflow/flutter-permission-handler#653]
## 💬 Questions and Help

For questions or help we recommend checking:

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

```   //检查是否有权限
  Future<bool> checkPermission() async {
    bool isStorage = true;
    bool isRequestInstallPackages = true;
    //检查是否已有读写内存权限
    PermissionStatus statusStorage = await Permission.storage.status;
    //允许安装未知权限
    PermissionStatus statusRequestInstallPackages =
        await Permission.requestInstallPackages.status;
    //判断如果还没拥有读写权限就申请获取权限
    if (statusStorage != PermissionStatus.granted) {
      isStorage = await Permission.storage.request().isGranted;
    }
    //判断允许安装未知权限
    if (statusRequestInstallPackages != PermissionStatus.granted) {
      isRequestInstallPackages =
          await Permission.requestInstallPackages.request().isGranted;
    }

    if (isStorage == true && isRequestInstallPackages == true) {
      return true;
    } else {
      return false;
    }
  }
```

我正在做安卓升级app 因为需要允许安装未知权限  故我去申请这个权限 但是 app会闪退 
flutter: 2.0.5
手机为:红米note9

**Comment by JDDV** [comment]
Hi @nayoTT, I was able to reproduce the same error. I've found the following information about it - [Click Here](https://www.androidpolice.com/2020/08/24/android-11-install-unknown-apps-more-cumbersome/)

The TL;DR version is that since Android version 11 kills the process when asked for this particulair permission.
Google stated "this is in fact working as intended.". Google explained it had to do with the new Scoped Storage.
I also saw [this Issue Tracker](https://issuetracker.google.com/issues/154157387?pli=1) from Google where people complained about this issue.

I tested the behavior on Android 10, and guess what, it worked as it was supposed to do. The app process didn't get killed by the OS. So this seems to be an Android 11 issue.

I will hereby close this comment, but feel free if you have any questions left!
