### ISSUE TITLE
Privacy - Local Network Usage Description

### ISSUE THREAD

**Issue by heroqin** [Baseflow/flutter-permission-handler#656]
Hi,
IOS14.0 add Privacy - Local Network Usage Description permission, as if permission_handler still don't support it?

**Comment by njovy** [comment]
@mvanbeusekom I've been using this plugin since it came out and every permission is in plugin until 
 I need local network permission. I have a new flutter app using WebRTC that requires a network permission. It is true that this permission doesn't require developers to use this permission but my app requires this for ICE. Please re-consider to add this!

**Comment by mvanbeusekom** [comment]
Hi @njovy, first of all thank you for using the plugin. It is always nice to hear people are happily using it for such a long time.

Regarding your question, I am not sure how to add this to the permission_handler. Apple doesn't provide an SDK for explicitly requesting these permissions. According to my understanding all you need to do is add the key to the `Info.plist` file and the rest will be taken care of by iOS. 

Of course if I am mistaken please point me to the correct documentation and I will happily reconsider.

**Comment by njovy** [comment]
@mvanbeusekom You are right there is no way to get local network permission at the moment. I guess I will find other way to check if this permission is granted or not. Thank you for the rapid response!

**Comment by nemanja-nisic** [comment]
@njovy Did you ever find a solution for this?
