### ISSUE TITLE
Permission.storage.isPermanentlyDenied returns wrong result

### ISSUE THREAD

**Issue by VladShturma** [Baseflow/flutter-permission-handler#670]
## 🐛 Bug Report

Call `await Permission.storage.request()` so to make permission asking pop-up show. Deny permission. After that subsequent call to `await Permission.storage.request().isPermanentlyDenied` won't trigger pop-up show, but just return `true`. As expected.
However call to `await Permission.storage.isPermanentlyDenied` returns `false` instead of `true`.

### Expected behavior

Expected that `await Permission.storage.isPermanentlyDenied` and `await Permission.storage.request().isPermanentlyDenied` both return `true`

### Reproduction steps

Like in description

### Configuration

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale en-RU)

**Version:** 8.1.6

**Platform:** 
- [ ] :robot: Android 11. Xiaomi Redmi Note 9 Pro MIUI Global 12.5.1 stable

**Comment by sky1095** [comment]
+1

**Comment by mvanbeusekom** [comment]
@VladShturma, @sky1095, this is unfortunately expected behaviour. 

The Android SDK doesn't provide support for checking if permissions are permanently denied or simply denied. The `ContextCompat.checkSelfPermission()` method only returns `PERMISSION_GRANTED` or `PERMISSION_DENIED` and there is no other API we can investigate to query if permissions are denied permanently (more information can be found in the [official Android documentation](https://developer.android.com/training/permissions/requesting#already-granted)). 

By using a small trick we are only able to reliable determine if permissions are denied permanently directly after permissions are requested. That is why the `Permission.storage.request().isPermanentlyDenied` is working while the `Permission.storage.isPermanentlyDenied` is not.

More information including the recommended way of handling permissions can be found in [this Wiki article](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0#breaking-changes).

I will close this issue as things are working as expected. Although it is not the most desirable solution, it is all we can do with the means given to us by the Android developers at Google.

**Comment by VladShturma** [comment]
@mvanbeusekom Thank you for quick reply and clarification!
