### ISSUE TITLE
Open setting and await its return

### ISSUE THREAD

**Issue by saileshbro** [Baseflow/flutter-permission-handler#677]
## 🚀 Feature Requests
Can we await the openSetting call so that it will resolve after it is returned to the app?

### Contextualize the feature
It will be helpful if we need to re check the permissions and continue from there.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @saileshbro,

Unfortunately this is not possible. Both the Android and iOS SDKs don't offer support for this. The best way to tackle this problem is to listen for App life cycle events as your App will be paused when the settings page is opened and resume when the user navigates back to your App. 

One way to listen to app life cycle events would be by adding the `WidgetsBindingObserver` mixin to the main widget and override the `didChangeAppLifecycleState` method. A detailed explanation can be found in this [article](https://medium.com/pharos-production/flutter-app-lifecycle-4b0ab4a4211a).
