### ISSUE TITLE
permissionNames.add(Manifest.permission.BLUETOOTH_CONNECT)

### ISSUE THREAD

**Issue by swarup13** [Baseflow/flutter-permission-handler#694]
permissionNames.add(Manifest.permission.BLUETOOTH_CONNECT)Execution failed for task permission_handler:compileDebugJavaWithJavac

compileSdkVersion 30

**Comment by JDDV** [comment]
Hi @swarup13, can you try to change the compileSdkVersion to 31 since the Bluetooth_Connect (and Scan, and Advertise) are new since SDK version 31. This should solve your problem!

In the [CHANGELOG](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md#822) you can see that there is some additional information about it in the [README](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) file.

I will close this issue for now, since I think this will solve your issue. Let me know if it did not!
