### ISSUE TITLE
 error: cannot find symbol permissionNames.add(Manifest.permission.BLUETOOTH_CONNECT);

### ISSUE THREAD

**Issue by liveaffiliates** [Baseflow/flutter-permission-handler#697]
## 🐛 Bug Report

Error:

  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
/Users/xxxx/Development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.2/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:272: error: cannot find symbol
                    permissionNames.add(Manifest.permission.BLUETOOTH_CONNECT);

### Expected behavior

Unknown

### Reproduction steps

Just started happening on android. No changes to anything. Was building one minite, next minute error occured with no changes.

Error says bluetooth permission but I only use NFC no bluetooth.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [Oppo Reno 3 ] :robot: Android

Thanks

**Comment by mvanbeusekom** [comment]
Make sure you set the `compileSdkVersion` in the `android/app/build.gradle` to `31`.

This is also documenten in the CHANGELOG.md (see version 8.2.0) and in the "Android" section of the README.md file.

**Comment by xixixx** [comment]
error: cannot find symbol
permissionNames.add(Manifest.permission.BLUETOOTH_CONNECT);

I had the same question but  when I  set compileSdkVersion=31 is useless

**Comment by mvanbeusekom** [comment]
@xixixx if you are working with Flutter Add-to-app please read this [issue](https://github.com/Baseflow/flutter-permission-handler/issues/704) carefully. 

Otherwise make sure you update the correct build.gradle file and add the `compileSdkVersion` using the correct syntax: 

1. You should update the `android/app/build.gradle` file;
2. Add `compileSdkVersion 31` just below the `android` block:

```gradle
android {
    compileSdkVersion 31
```

for a complete example have a look [here](https://github.com/Baseflow/flutter-permission-handler/blob/56e58fa2c55df330d82cba7c07037b1288a4e779/permission_handler/example/android/app/build.gradle).
