### ISSUE TITLE
First call permission. Photos. Request(); Why is the system pop-up not displayed

### ISSUE THREAD

**Issue by cctvbtv123456** [Baseflow/flutter-permission-handler#699]
First call permission. Photos. Request(); Why is the system pop-up not displayed    verison  : 8.1.6

**Comment by cctvbtv123456** [comment]
iOS  、
The version I used before was relatively low, and the functions were good. The problem occurred when I upgraded to 8.1.6

iOS/Podfile：

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# 使用当前项目私有源
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

inhibit_all_warnings!

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

install! 'cocoapods',
         :disable_input_output_paths => true,
         :warn_for_multiple_pod_sources => false

# 共同的pod
def commonPods
    pod 'TZImagePickerController', :git => 'https://github.com/banchichen/TZImagePickerController.git', :tag => '3.2.10'
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'Runner' do
    commonPods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by mvanbeusekom** [comment]
@cctvbtv123456 The problem seems to be that you need to enable permissions you want to use. The best way to do so is add configuration in you `ios/Podfile` (new since version 8.0.0). Documentation can be found in the "iOS" section of the [README](https://github.com/Baseflow/flutter-permission-handler/blob/57bd9f528f7c83ade2f71c015b065b1c410f4b77/permission_handler/README.md) file. 

You can also have a look at the [ios/Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/57bd9f528f7c83ade2f71c015b065b1c410f4b77/permission_handler/example/ios/Podfile) in our example App.

I will close the issue now. If you keep on having issues please leave a comment and I will do my best to help.
