### ISSUE TITLE
[iOS] permission alert not displayed on Retry 

### ISSUE THREAD

**Issue by erperejildo** [Baseflow/flutter-permission-handler#718]
This was working fine before update to 8.2.5.

<img width="234" alt="Screenshot 2021-11-02 at 18 29 14" src="https://user-images.githubusercontent.com/5629919/139915749-9c0f4f0f-df35-4a9a-95d6-a13d38135864.png">

I have this code showing the Retry button:

```
TextButton(
              onPressed: () async {
                await _checkPermission().then(
                  (hasGranted) {
                    if (hasGranted == PermissionStatus.granted) {
                      refreshContacts();
                    }
                  },
                );
              },

...

Future<PermissionStatus> _checkPermission() async {
    final Permission permission = Permission.contacts;
    final status = await permission.request();
    return status;
  }
```

and that always returns:
`PermissionStatus.permanentlyDenied`

but it doesn't open the permission question again.

Info.plist:
```
<key>NSContactsUsageDescription</key>
<string>This app requires access to display the contacts list. This will be used to import contacts automatically if necessary to the app contacts list.</string>
```

`compileSdkVersion 31`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by mvanbeusekom** [comment]
Hi @erperejildo,

Did you update from a version before 8.0.0 by any change? If so you will need to change the configuration in your `ios/Podfile`.

In versions before 8.0.0 permissions on iOS are enabled by default and you would use the configuration in the `ios/Podfile` to disable permissions you don't need in your App. Since version 8.0.0 we flipped the default behaviour, meaning permissions are disabled by default and you would need to configure your `ios/Podfile` correctly to enable the permissions you need in your App. Permissions that are not enabled explicitly will always directly return the `PermissionStatus.permanentlyDenied` status. 

This was done because of two reasons:

1. Protect users from listing all permissions in their `ios/Runner/Info.plist` and risk rejection on the Apple App Store;
2. Ensure that we don't have to introduce a breaking change each time we introduce a new permission.

Details instructions can be found in the "iOS" section of the [README.md](https://pub.dev/packages/permission_handler). The change in behaviour is also mentioned in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#800).

Please let me know if this is the case.

**Comment by akhiljohny** [comment]
post_install do |installer|
installer.pods_project.targets.each do |target|
flutter_additional_ios_build_settings(target)
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',
## dart: PermissionGroup.camera
'PERMISSION_CAMERA=1'
]
end
end
end

Add this in pod file and delete pod lock and pod install then it will work

**Comment by sanirasheed** [comment]
Thanks that worked! used this to enable Contacts permissions

**Comment by canb0** [comment]
https://github.com/Baseflow/flutter-permission-handler/issues/718#issuecomment-1177231123 Worked like a charm! Saved my day
