### ISSUE TITLE
Bluetooth permission feature on Android 12 not working

### ISSUE THREAD

**Issue by kaciula** [Baseflow/flutter-permission-handler#730]
## 🐛 Bug Report

Asking for bluetooth permission on Android 12 does not seem to work. I see that this plugin outputs the following log message "Bluetooth permission missing in manifest" but I have all bluetooth permissions declared in the AndroidManifest.

### Expected behavior
Show bluetooth permission dialog

### Reproduction steps
Run device with Android 12 and ask for bluetooth permission

### Configuration

I have this in my AndroidManifest.xml. I triple checked that these permissions are included in the final merged manifest.

`

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
`
    
The merged manifest modifies my BLUETOOTH permission to
 `
<uses-permission
        android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
`

Some other plugin is modifying the manifest. However, Google's official site says to add the maxSdkVersion param. (https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) So I expect this plugin to work with this param.

Anyway, if I remove that plugin and there is no maxSdkVersion param attached, the permission_handler is not showing any permission dialog and says the status is granted. But if I go into the phone's settings and look at the permissions, I see that the Nearby Devices permission (aka bluetooth) is denied. Althugh I never denied it or even seen a permission dialog.

So something is definitely not right here.

**Version:** 8.2.6

**Platform:** 
 Android 12 emulator using Sv2 image

**Comment by juanmendez** [comment]
hi, I set my manifest permissions like this:
```
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
I am using this library `device_info` to do the following
```
  Future<bool> _usesAdditionalBlePermissions() async {
    if (Platform.isAndroid) {
      final packageInfo = await DeviceInfoPlugin().androidInfo;
      final sdk = packageInfo.version.sdkInt;
      return sdk >= 31;
    }

    return false;
  }
```

So I am using a future builder so that way I can determine if true or false,, and what permission to request next.. 
I am using a stream builder as well which is looking for each permission needed.. what I found out is that if I let scan permission as accepted, the rest of the permissions are also granted... not sure why, but I still let the app verify each permission.. sounds like a lot of work for what I am doing but it works. 

If you don't do the distinction and request bluetooth permission in Android 12 then you get that permission as permanently denied, and in the logcat it shows the permission is not listed in the manifest file.

If you have any other questions let me know.

**Comment by kaciula** [comment]
@juanmendez Thanks for the info. My mistake was that I was asking for bluetooth permission on Android 12. I should ask for bluetoothScan / bluetoothAdvertise / bluetoothConnect permissions.
