### ISSUE TITLE
App crashes when changing contacts permission from device settings on iOS

### ISSUE THREAD

**Issue by monster555** [Baseflow/flutter-permission-handler#746]
## 🐛 Bug Report

App crashes when changing contacts permission from device settings on iOS, not tested on Android yet.

### Configuration

**Version:** 8.3.0

**Platform:** 
- [ X ] :iphone: iOS
- [ ] :robot: Android

**Comment by florissmit1** [comment]
Although it's not clearly documented by Apple, this is expected behaviour. The app will be killed (The `SIGKILL` command will be executed) when running in the background and changing the permissions, this will only occur when using the Simulator.  When using a iOS device, the app will be restarted in the background by the system.
