### ISSUE TITLE
How to request READ_EXTERNAL_STORAGE?

### ISSUE THREAD

**Issue by StiffFy** [Baseflow/flutter-permission-handler#751]
Permission.storage.request()  just request WRITE_EXTERNAL_STORAGE, how can i request READ_EXTERNAL_STORAGE?

**Comment by JDDV** [comment]
Hi @StiffFy, the `Permission.storage.request()` requests the `READ_EXTERNAL_STORAGE`, and not `WRITE_EXTERNAL_STORAGE`. This is due to the fact that `WRITE_EXTERNAL_STORAGE` does not need to asked for permission since Android version 4.4. Google's documentation about this subject says the following:

```
The highest API level at which this permission should be granted to your app. 
Setting this attribute is useful if the permission your app requires is no longer needed beginning at a certain API level.
For example, beginning with Android 4.4 (API level 19), it's no longer necessary for your app to request the
WRITE_EXTERNAL_STORAGE permission when your app wants to write to its own application-specific directories on external
storage (the directories provided by getExternalFilesDir()). However, the permission is required for API level 18 and lower. 
So you can declare that this permission is needed only up to API level 18 with a declaration such as this:
```
 
I hope this answered your question, I'll close this issue for now but let me know if you have any questions!
