### ISSUE TITLE
 How to change the language of the permission request

### ISSUE THREAD

**Issue by DelfosTI** [Baseflow/flutter-permission-handler#768]
## 💬 Questions and Help

For questions or help we recommend checking:

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

Hello, how are you? I wanted to know how I can change the language of the alert since it comes out in English by default on Android
![image](https://user-images.githubusercontent.com/85813700/148858943-7c7f48e8-2d17-42b0-84fc-a449899bd704.png)

**Comment by JDDV** [comment]
Hi @DelfosTI, Android permission is not on default on English. It is set on the language your phone is set on. For example, if in the settings screen your language of the phone is set on Spanish the permission will look like this:

![image](https://user-images.githubusercontent.com/47666699/149327558-c529a5cc-921a-4d3d-953e-a2648fd586bb.png)

I tested this by using the emulator on a Pixel 4 running on Android 11.
I'll close this issue for now since I think this answer will help you out, if you still have questions regarding this topic then please feel free to comment!
