### ISSUE TITLE
Location permission on iOS is always permanentlyDenied although it used to work correctly before

### ISSUE THREAD

**Issue by kaciula** [Baseflow/flutter-permission-handler#775]
### Old (and correct) behavior

I would request for location permission and I would see a Location dialog.

### Current behavior

Requesting the location permission on app's first launch gives permanentlyDenied status. If I go to app's settings, I don't even see the Location permission option to manually change it. My Podfile has 'PERMISSION_LOCATION=1'

It used to work and I haven't changed the permission code or ios files at all. The only thing I did was to update ios to 15.2.1. I can't remember what ios version I had before. Both real devices and simulators behave the same.

The plugin also says the location service is disabled although I can see in the phone's settings that it is enabled for other apps.

### Reproduction steps

Test on ios 15.2.1 and request location permission.

### Configuration

**Version:** 8.3.0.

**Platform:** 
- [x ] :iphone: iOS 15.2.1

**Comment by EvGeniyLell** [comment]
did you try some from this at your podfile?
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
#        'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
#        'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
#        'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
#        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
#        'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
#        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
#        'PERMISSION_LOCATION=1',
       
        ## dart: PermissionGroup.notification
#        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
#        'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth
#        'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
#        'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
#        'PERMISSION_CRITICAL_ALERTS=1',
      ]

    end
  end
end
```

**Comment by kaciula** [comment]
@EvGeniyLell Yes. I've mentioned in my original post that I have 'PERMISSION_LOCATION=1' in my Podfile. It used to work before the ios and xcode update and I haven't modified anything in my Podfile since then.

**Comment by RibuRoyson** [comment]
same problem for me also..everything worked fine till yesterday.

**Comment by RibuRoyson** [comment]
whenever i changed permission_location = 1 and run the project its says Warning: CocoaPods not installed. Skipping pod install.CocoaPods not installed or not in valid state.
Error launching application on iPhone 13. flutter doctor did't find any issues. I can run the project from terminal also theres no issues. Issue is running from android studio.

**Comment by RibuRoyson** [comment]
> @EvGeniyLell Yes. I've mentioned in my original post that I have 'PERMISSION_LOCATION=1' in my Podfile. It used to work before the ios and xcode update and I haven't modified anything in my Podfile since then.

Hi i changed the permission_handler to 7.0.0 and launch the android studio through terminal now everything is working as expected. Also i changed the flutter version from 2.2.2 to 2.5.0.

**Comment by kamami** [comment]
I have the same issue with `flutter 2.10` and `permission_handler 8.3.0`.
There is currently no way to get the `locationAlways` permission.

**Comment by EvGeniyLell** [comment]
try `pod install --repo-update` and recheck the plugin file `project.pbxproj` you should have some like this
```
GCC_PREPROCESSOR_DEFINITIONS = (
  "$(inherited)",
  "PERMISSION_LOCATION=1",
);
INFOPLIST_FILE = "Target Support Files/permission_handler/permission_handler-Info.plist";
```
because if you don't have the in `project.pbxproj` it is not a problem with the plugin
it is the wrong `podfile` script.
if `PERMISSION_LOCATION=1` in your `project.pbxproj` you will always have `permanentDenide`
because the preprocessor flag for on/off code parts in the plugin on compilation time.

now i use the latest versions of all (Flutter/iOS/Xcode/IntelliJ/CocoaPods and permission_handler)
but it related only to CocoaPods because it depended only on `podfile`
i have the  next`podfile` script
```
# Uncomment this line to define a global platform for your project
platform :ios, '12.1'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      if config.build_settings['PRODUCT_NAME'] == 'permission_handler'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          'PERMISSION_LOCATION=1',
        ]
      end
    end
  end
end
```
and i don't have any problem.
please don't forgot `pod install --repo-update`

**Comment by kamami** [comment]
I did `pod install --repo-update` but there is no 
```
GCC_PREPROCESSOR_DEFINITIONS = (
  "$(inherited)",
  "PERMISSION_LOCATION=1",
);
INFOPLIST_FILE = "Target Support Files/permission_handler/permission_handler-Info.plist";
```

in my `project.pbxproj`. 

I did not forget to add   `"PERMISSION_LOCATION=1"`, to my `Podfile`

**Comment by kaciula** [comment]
@EvGeniyLell It was indeed a Podfile issue. There was some code from a different plugin that was also manipulating the GCC_PREPROCESSOR_DEFINITIONS. After removing that code, the permissions are now available inside the app.

**Comment by kamami** [comment]
I have only this in my podfile related to `GCC_PREPROCESSOR_DEFINITIONS` and it is still not working:

```
  target.build_configurations.each do |config|

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0',
        'PERMISSION_LOCATION=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_CAMERA=1',
        'PERMISSION_SENSORS=1'
      ]

    end
```

**Comment by naderhezzy** [comment]
> @EvGeniyLell It was indeed a Podfile issue. There was some code from a different plugin that was also manipulating the GCC_PREPROCESSOR_DEFINITIONS. After removing that code, the permissions are now available inside the app.

@kaciula Can you please name the plugin that was also manipulating the GCC_PREPROCESSOR_DEFINITIONS !
i have the same issue and this may help (because i'm using several plugins).
Thank you

**Comment by kaciula** [comment]
@naderhezzy Just look in the Podfile and see where else GCC_PREPROCESSOR_DEFINITIONS is being used. I don't know the exact package but it was definitely one related to permissions also. Maybe a speech to text package that needed microphone permission.

**Comment by EvGeniyLell** [comment]
as i mentioned above your pod file should be like
```bash
# some other code
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # some other code

    target.build_configurations.each do |config|
      if config.build_settings['PRODUCT_NAME'] == 'permission_handler'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          'PERMISSION_LOCATION=1',
        ]
      end
    end

    # some other code
    # if you need do changes like GCC_PREPROCESSOR_DEFINITIONS
    # do this with if config.build_settings['PRODUCT_NAME'] == 'SOME_NAME'
    # for protect unneded changes in other plugins

  end
end
```

**Comment by kamami** [comment]
I have only one `GCC_PREPROCESSOR_DEFINITIONS ` in my pod file and still get the issue described above.

**Comment by naderhezzy** [comment]
Thank you guys for your response, i appreciate your help initiative.

@kaciula I'm using Location package but not for permissions, only for getting user's location, knowing that this plugin can ask for the location permission but i'm using permission_handler for this task to avoid permission request conflict, therefore, i don't see the GCC_PREPROCESSOR_DEFINITIONS used anywhere else by other plugin in the my podfile.

@EvGeniyLell  Actually i'm not understanding this line in your code:

` if config.build_settings['PRODUCT_NAME'] == 'permission_handler'`

i don't know if it's required for me since i can't find it in the official example's podfile
here's my full podfile in case you need to have a look on it

`# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Custom config
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

      ]
    end
  end
end
`

Now i'm using the latest version of:
-  Flutter (2.10.1)
- permission_handler (9.0.1)

Tested on IOS 15.3/13 (Real devices)

& thank you again.
