### ISSUE TITLE
Permission Status always return Denied.

### ISSUE THREAD

**Issue by jlzapata** [Baseflow/flutter-permission-handler#777]
## 🐛 Bug Report

Check Permission Status always returns `denied` when it should returns `permanentlyDenied` when the OS doesn't prompt the
permission dialog anymore after deny multiple times the request.

### Expected behavior
Returns `permanentlyDenied` when deny the request multiple times.

### Reproduction steps
Request permission with `Permission.storage.request` and deny until the OS doesn't prompt the dialog anymore. 

### Configuration
Android Version: 11 RP1A.200720.011

**Version:** 8.3.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by jlzapata** [comment]
> ## 🐛 Bug Report
> Check Permission Status always returns `denied` when it should returns `permanentlyDenied` when the OS doesn't prompt the permission dialog anymore after deny multiple times the request.
> 
> ### Expected behavior
> Returns `permanentlyDenied` when deny the request multiple times.
> 
> ### Reproduction steps
> Request permission with `Permission.storage.request` and deny until the OS doesn't prompt the dialog anymore.
> 
> ### Configuration
> Android Version: 11 RP1A.200720.011
> 
> **Version:** 8.3.0
> 
> **Platform:**
> 
> * [ ]  📱 iOS
> * [x]  🤖 Android

**Comment by jlzapata** [comment]
Flutter version: 2.8.1

**Comment by mvanbeusekom** [comment]
Hi @jlzapata,

This is expected behavior as Android doesn't provide this information to developers. When checking permissions Android will only return `granted` or `denied` and doesn't distinguish between permanently denied permission or denied and try again.

We used to have a workaround implemented but starting Android API 30 this was causing a whole new range of problems.

- More information regarding this topic and a recommended sample can be found on our [wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0#breaking-changes) page.
