### ISSUE TITLE
App crashes after manually deny a permission, it freezes in the splash screen.

### ISSUE THREAD

**Issue by diegoVegaLoro** [Baseflow/flutter-permission-handler#779]
🐛 Bug Report
I'm trying to test a new app and requesting location and contacts permission for it. After requesting and allowing the location and contacts permissions, when I deny those permissions on app settings, the app crashes and stay freeze in the splash screen.

Expected behavior
It should not crash when i manually deny the permissions.

Reproduction steps
1- Request permissions
2- Allow permissions
3- Manually go to app settings and deny the permisisons
4- App crashes.

Configuration
Version: ^8.3.0

Platform:

[ x ] 📱 iOS
[ x ] 🤖 Android

**Comment by mvanbeusekom** [comment]
Hi @diegoVegaLoro,

Unfortunately this is expected behavior on iOS and devices running Android 12.  

On Android 12 the this happens when downgrading location permissions from "Precise" to "Approximate" and is [documented](https://developer.android.com/training/location/permissions#approximate-request) as follows:

> **Caution:** If the user downgrades your app's location access from precise to approximate, either from the permission dialog or in system settings, the system restarts your app's process. For these reasons, it's especially important that you follow best practices for requesting runtime permissions.

Although it's not clearly documented by Apple, on iOS the app will be killed (The `SIGKILL` command will be executed) when running in the background and changing the permissions, this will only occur when using the Simulator.  When using an iOS device, the app will be restarted in the background by the system. 

This behaviour is described in a WWDC sheet on page 24, see: [link](https://download.developer.apple.com/wwdc_2012/wwdc_2012_session_pdfs/session_710__privacy_support_in_ios_and_os_x.pdf), and is described as follows:

- If permissions changes, the app is quit:
■ Background task expiration handler is called, if registered
■ iOS then kills the application

Let me know if you have any further issues, for now I will close this issue.
