### ISSUE TITLE
Error in multipleRequest above android 10 

### ISSUE THREAD

**Issue by Bhuvanesh-Creator** [Baseflow/flutter-permission-handler#785]
For android version above 10, the permission which call like:
Map<Permission, PermissionStatus> statuses = await [ Permission.contacts,  Permission.location,Permission.sms, ].request(); 
was not working it show permentlydenied in console before the dialouge shows.

**Comment by JeroenWeener** [comment]
Hi @Bhuvanesh-Creator, thank you for taking the time to file this issue.

I have tried to reproduce your issue using `permission_handler` `10.4.1` on Android emulators, running Android API levels 29, 30 and 33 (Android 10, 11 and 13, respectively). Unfortunately, I was unable to reproduce the issue.

My code: https://gist.github.com/JeroenWeener/881f711502fbcd27a3667bb82d3f0680

Running the code:

https://github.com/Baseflow/flutter-permission-handler/assets/9049645/cb6f7cc8-6506-47af-8d16-9782b9ef4ba4


Could you verify whether you are still experiencing your issue on the newest version of the permission handler plugin (10.4.1 at the time of writing)? If the issue persists, I want to invite you to send a minimal reproducible code sample. That way, we can look into the root cause of the issue more effectively.
