### ISSUE TITLE
Android: Contacts Permission Status

### ISSUE THREAD

**Issue by TomerPacific** [Baseflow/flutter-permission-handler#808]
## 🐛 Bug Report
When requesting the contacts permission and the user has decided to permanently deny it, the behavior of the service is inconsistent.
After this has happened, when you call the API:

`Permission.contacts.status`

you get a PermissionStatus of **_denied_** (even though it should be permanently denied).

Only after calling:
`Permission.contacts.shouldShowRequestRationale`
the permission status changes to  permanently denied.

If I use this logic in my application (I.E. in a service), the user gets prompted for the permission when the application starts and not when his/her actions require him/her to do so). So that is not a desired solution. 

### Expected behavior
I believe that after a user has permanently denied a permission, it should always return that status for it.
### Reproduction steps
- Open application ad get the permission status for contacts
- If it is denied, request permission from user
- Choose to deny the permission
- Request contacts permission again
- Choose to Deny & don't ask again (permanently deny permission)
- Open application again and check status of contacts permission (it will be denied and not permanently denied)
### Configuration

**Version:** 9.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @TomerPacific, 

This is unfortunately expected behaviour. The Android permission SDK allows for checking permissions but will only return a `GRANTED` or `DENIED` status. Android doesn't provide any SDK to check if permissions are permanently denied. 

Using the `shouldShowRequestRationale` workaround we are able to return the `permanentlyDenied` status as a result of requesting permissions but that is the only time we are able to distinguish between the `denied` and `permanentlyDenied` states. 

Best workflow would be to check permissions and request permission when the status returned is `denied`. If the end user permanently denied permissions earlier the permission popup will not show up and the result of the `request()` method will be `permanentlyDenied`.

This is explained in more detail on our [Wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) page.
