### ISSUE TITLE
If location is set on battery saving (GPS off), checkPermissionStatus returns ServiceStatus.enabled

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-permission-handler#85]
## 🐛 Bug Report
In Android, when you have location set to Battery Saving, and you check for service status using 
```
ServiceStatus status = await PermissionHandler().checkServiceStatus(PermissionGroup.locationWhenInUse);
```
The status returned is `ServiceStatus.enabled`. 

### Expected behavior
The status returned should be `ServiceStatus.disabled` because Battery saving doesn't show location updates. 

### Solution
You need to use something like this in your java code
```
LocationManager locationManager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
boolean isGpsOn = locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
```
The value of `isGpsOn` is `true` for 
1. High accuracy
2. Device only

and `false` for Battery saving mode

![image](https://user-images.githubusercontent.com/40364434/53901168-492b6a00-4064-11e9-8683-94f9308e63a7.png)

### Version
version: "3.0.0"

**Platform:** 
Android

**Comment by mvanbeusekom** [comment]
@dark-chocolate sorry for the late reply, it has been busy weeks again. 

I am a bit puzzled by this request, since the location services are enabled (I am simply returning what Android is telling me when asking if location services are enabled) and also the description with the "Battery saving" mode states "Use Wi-Fi and mobile networks to determine location".  

To me this means that location services do work, just the accuracy is not so high (since Android is using only using Wi-Fi and mobile networks). So returning `ServicesStatus.disabled` would be incorrect in my opinion. 

Wouldn't it be better to add another value to the enumeration (something like `ServiceStatus.batterySaving` or `ServiceStatus.lowAccuracy`)?

**Comment by dark-chocolate** [comment]
@mvanbeusekom I agree with you, `ServicesStatus.disabled` would be incorrect, instead we should be using as you said `ServiceStatus.batterySaving`.

**Comment by sd-timaru** [comment]
It will be great if this plugin will return the Location mode : High Accuracy, Battery saving, Device only.

**Comment by shivangg66** [comment]
how do i write java code in flutter

**Comment by JDDV** [comment]
Due to inactivity I closed this issue, if you would like to see this feature in the permission handler we would love to see a feature proposal!
