### ISSUE TITLE
Bad management of Bluetooth permission for android >= 12

### ISSUE THREAD

**Issue by vricosti** [Baseflow/flutter-permission-handler#868]
## 🐛 Bug Report

When trying to use Bluetooth Low Energy on android 12 I cannot make it work on my Pixel 3 running android 12 and I have a message inside debug console:

permissions_handler(15297): Bluetooth permission missing in manifest 

### Configuration

**Version:** 1.0.0

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android

I have rooted my phone and examined well known BLE applications and in their manifest there are generally these permissions:

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
```

I am using the following parameters:

c:\myapp\android\app\build.gradle

```
android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.johndoe.myappdemo"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}
```

I don't know if this error message is important or not but at the end I cannot scan ble devices.

UPDATE: actually my app was relying on Permission.bluetooth to know if we have access to the bluetooth but on android 12 it returns false, so I don't really know if flutter_permissions needs to provide some kind of abstraction or if an app need to to some specific code... I would personnaly this to be handled inside this plugin.

**Comment by vricosti** [comment]
Anyway at the end I am not able to scan ble devices

**Comment by vricosti** [comment]
Finally I fixed it on my side by writing something like that:

```
Future<int> getAndroidSdk() async {
    DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
    return androidInfo.version.sdkInt ?? 30;
  }

  Future<bool> requestBluetoothAccess() async {
    Future<bool> permStatus;
    if (Platform.isAndroid && await getAndroidSdk() > 30) {
      permStatus = _requestAccess(Permission.bluetoothScan);
      _requestAccess(Permission.bluetoothConnect);
    } else {
      permStatus = _requestAccess(Permission.bluetooth);
    }
    return permStatus;
  }
```

I think it would be better if you could put this kind of logic inside your plugin and it would avoid me to get sdk version on runtime.

**Comment by iandis** [comment]
For the `android.permission.BLUETOOTH`, you might need to consider a few Manufacturers that misimplemented the new Android Bluetooth permission specs for Android 12+ like Xiaomi.
This happened to me trying to connect to an already-paired Bluetooth device using MIUI12 Android 12 where the `Bluetooth permission missing in manifest` was thrown even though I have declared `android.permission.BLUETOOTH_CONNECT`. It turned out I still needed `android.permission.BLUETOOTH`.

**Comment by JDDV** [comment]
Hi @vricosti, can you provide me a minimal code example so I can reproduce the issue? I've tried on both my physical and emulator phone on Android >= 12, and I don't get the error message `permissions_handler(15297): Bluetooth permission missing in manifest.`. But I might do something different than what you do.

> For the `android.permission.BLUETOOTH`, you might need to consider a few Manufacturers that misimplemented the new Android Bluetooth permission specs for Android 12+ like Xiaomi. This happened to me trying to connect to an already-paired Bluetooth device using MIUI12 Android 12 where the `Bluetooth permission missing in manifest` was thrown even though I have declared `android.permission.BLUETOOTH_CONNECT`. It turned out I still needed `android.permission.BLUETOOTH`.

I've noticed too that this is happening by some manufacturers, thanks for pointing it out as well since some people might have issues with it. I assume however that Google has the implementation correct unlike XiaoMi, since @vricosti said he tested it on the Pixel 3.

**Comment by vricosti** [comment]
Actually since I have modified my manifest I cannot see this error anymore, just find it somewhat annoying that I have to manage it myself with the code I posted on my previous message (see requestBluetoothAccess() )

**Comment by JDDV** [comment]
I'm glad it works since you modified your manifest!
By default the Android 12 Bluetooth permissions (bluetooth.connect, bluetooth.scan, bluetooth.advertise) are granted on lower Android versions. Lower Android versions do need the bluetooth and bluetooth admin permission in the manifest though (but no need to ask for the permission since it is granted by default).

If you run your app asking for the bluetooth connect, scan & advertise permission on lower android versions, there will be no pop-up dialog and those permissions are granted by default. So your code that you provided can be optimized.

```
//Get android SDK method is not necessary, since on API 30 and lower Bluetooth permission will be just granted
//If permission is added in the manifest that is. 

  bool requestAccess() async {
    //request here your permissions
    
    bool permOne = await Permission.bluetoothScan.request().isGranted;
    bool permTwo = await Permission.bluetoothAdvertise.request().isGranted;
    bool permThree = await Permission.bluetoothConnect.request().isGranted;

    //This will only bring up one permission pop-up, but will only grant the permissions you have been requested here
    //in this method.

    //Return your boolean here
    return permOne && permTwo && permThree ? true : false;
  }
```

you could do something along those lines, instead of the code snippet you've shown. I tested it real quick and for me it worked.

I'm glad it is solved anyways, this issue will be closed for now! feel free to reply if there are still some questions!

**Comment by typexy** [comment]
> you could do something along those lines, instead of the code snippet you've shown. I tested it real quick and for me it worked.

What exactly did you change in your manifest?

**Comment by Karmalakas** [comment]
> Actually since I have modified my manifest I cannot see this error anymore

@vricosti, what exactly did you change?
