### ISSUE TITLE
Android return denied status for some iOS permissions.

### ISSUE THREAD

**Issue by kyuqw** [Baseflow/flutter-permission-handler#879]
## 🐛 Bug Report

Android return denied status for some iOS only permissions.
- photosAddOnly
- appTrackingTransparency
- criticalAlerts

### Expected behavior
return granted status

**Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
This is behaviour as it is expected. Those permissions are not available for Android, hence the reason why they return the `denied` status. The user can't allow those permissions on Android phones, so returning the `granted` status is more confusing since the user didn't/can't grant permission. it is documented for the permissions as well that it does nothing on Android.

**Comment by kyuqw** [comment]
Then why photos return the granted status?
