### ISSUE TITLE
Does the "iOS: Nothing" mean " permission != PermissionStatus.granted" ?

### ISSUE THREAD

**Issue by XinyueZ** [Baseflow/flutter-permission-handler#900]
Hey, need help to get official answer.

I  have seen that some APIs have been documented with the `iOS: Nothing` and there isn't additional information about if it turns to the state like `permissionStatus.granted` or not.

``` dart
  ///Android: Allows the user to look for Bluetooth devices
  ///(e.g. BLE peripherals).
  ///iOS: Nothing
  static const bluetoothScan = Permission._(28);

  ///Android: Allows the user to connect with already paired Bluetooth devices.
  ///iOS: Nothing
  static const bluetoothConnect = Permission._(30);
```

So I run the following codes:

```dart
    final permission = await Permission.bluetoothScan.request();
    print("'bluetoothScan': ${permission == PermissionStatus.granted}");
    return permission == PermissionStatus.granted;
```

The print is `false`.

Why don't you internally do platform check like at `request()` for such `iOS: Nothing` permissions?

```dart
   if (defaultTargetPlatform != TargetPlatform.android) {
      return false;
    }
```

thank you

**Comment by TimHoogstrate** [comment]
Dear @XinyueZ,

Thanks for your question. That is because we wanted to keep the top layer of the plugin similar for iOS and Android. However, some may only exist op iOs or some may only exist in Android. This means that we sometimes cannot check is a permission is available on a specific platform. Therefore, we return false (as a default value). If is implemented this way to help the developer to be able to implement a feature easier.

Kind regards,
