### ISSUE TITLE
Please remove the use of REQUEST_INSTALL_PACKAGES permission from your app.

### ISSUE THREAD

**Issue by ahmadvicky** [Baseflow/flutter-permission-handler#935]
I got message from google play, but we not use it.

when I check request install packages come from here.

please help!!

**Comment by mvanbeusekom** [comment]
Hi @ahmadvicky,

How did you come to the conclusion the `REQUEST_INSTALL_PACKAGES is coming from the permission_handler plugin?

We have done extensive research (see issue #869) and cannot find any reason why the permission_handler would add this permission to any app.

If you have additional information please share it with us. Please also check [this comment](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1186913958) for instructions on finding more information where permissions might come from.

**Comment by KumarArab** [comment]
Hey, I got this warning from google play. I can see that only permisson_handler users this 
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/53944263/194783265-8b3f49bd-628a-4aac-958b-01183a293d33.png">

**Comment by ahmadvicky** [comment]
> Hey, I got this warning from google play. I can see that only permisson_handler users this
> <img alt="image" width="1113" src="https://user-images.githubusercontent.com/53944263/194783265-8b3f49bd-628a-4aac-958b-01183a293d33.png">

yes I am see like that.

but if you use open_file please open this https://stackoverflow.com/a/59857508


but my case on android 33.

<img width="565" alt="Screen Shot 2022-10-10 at 08 52 53" src="https://user-images.githubusercontent.com/25771147/194789948-3df12fa5-6535-4beb-a79d-d3eba11dd702.png">

after I am upgrade targetSdkVersion to 33 

<img width="917" alt="Screen Shot 2022-10-10 at 08 55 56" src="https://user-images.githubusercontent.com/25771147/194790205-0a525aaa-90f4-4428-8616-771e1113204c.png">

**Comment by ElKood-Sol** [comment]
Same here

**Comment by ElKood-Sol** [comment]
Temp fix here:
https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1249015831

**Comment by ahmadvicky** [comment]
> Temp fix here:
> [#869 (comment)](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1249015831)

thank you

**Comment by lakshydeep-14** [comment]
Hey I am using open file package and it is required in my application.
My application is rejected from play store saying "REMOVE REQUEST_INSTALL_PACKAGES".
Help me out?
What to add in manifest.xml file and what not so that my application will get accepted?

**Comment by mvanbeusekom** [comment]
Hi @lakshydeep-14,

I have already pointed out to you how to resolve this [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1285032623), [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1285128640) and [here](https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1287645695).

This is not a permission_handler issue but caused by the open_file package. If the workarounds don't work for you please raise an issue with the open_file maintainers or look for a replacement package (I understood the [open_filex](https://pub.dev/packages/open_filex) package doesn't required the REQUEST_INSTALL_PACKAGE permission).
