### ISSUE TITLE
Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by w13798976975** [Baseflow/flutter-permission-handler#947]
## 🐛 Bug Report

PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)

### Configuration

**Version:** 8.3.0
**Flutter SDK Version:2.8.1

**Platform:** 
- [ ] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @w13798976975, thank you for filing a bug report!

For us to dive into the root cause of this issue, we would need to know where to look. For that, could you provide a minimal reproducible code sample? You can quickly create one by running `flutter create`, tweaking the `main.dart` file, and posting its contents here directly, or via a [gist](https://gist.github.com/).

Looking forward to hearing from you!
