### ISSUE TITLE
how to remove Permissions REQUEST_INSTALL_PACKAGES 

### ISSUE THREAD

**Issue by prajapat9782** [Baseflow/flutter-permission-handler#994]
## 💬 REQUEST_INSTALL_PACKAGES

this package has request REQUEST_INSTALL_PACKAGES in androidManifest.xml.
how to remove REQUEST_INSTALL_PACKAGES permission so my app release on play console.

**Comment by mvanbeusekom** [comment]
This is not a permission_handler issue but caused by the another package. This topic is extensively discussed in issue #869. workaround are mentioned in comments https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1285032623, https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1285128640 and https://github.com/Baseflow/flutter-permission-handler/issues/869#issuecomment-1287645695.

If the workarounds don't work for you please raise an issue with the maintainers of the package introducing the permission or look for a replacement package. The open_file package is one of the packages known to cause this error, I understood the [open_filex](https://pub.dev/packages/open_filex) package doesn't required the REQUEST_INSTALL_PACKAGE permission.
