### ISSUE TITLE
flutter windows Building Nuget.exe not found, trying to download or use cached version.

### ISSUE THREAD

**Issue by striveenFei** [Baseflow/flutter-permission-handler#996]
## 💬 Questions and Help

Visual Studio Community 2019

If the "permission_handler" library is referenced, the following problems will be reported. If the "permission_handler" library is removed, the Windows version can be compiled normally, What should I do

Building Windows application...
Nuget.exe not found, trying to download or use cached version.

**Comment by eae1212** [comment]
the same error

**Comment by mvanbeusekom** [comment]
Hi @striveenFei, @eae1212,

This is usually caused by an configuration error regarding NuGet package manager. The permission_handler_windows package makes use of NuGet to download the `Microsoft.Windows.CppWinRT` library which contains is used to generate C++ header files to access the Windows native runtime SDK, needed to communicate with the permission system. 

I am not really sure what causes the configuration error, however here are some steps that can be verified:

1. Make sure the default NuGet configuration file exists at the following path `%appdata%\NuGet\NuGet.Config`. If it doesn't exists create it with the following contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
2. If the default `NuGet.Config` exists with the appropriate content, verify if you are allowed to connect to the `https://api.nuget.org/v3/index.json` url. Some organisations are configured behind a firewall or proxy blocking access.
3. Make sure [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) (not Visual Studio Code) is installed correctly with the "Desktop development with C++" workload including all default options.

If this all fails please run `flutter build windows -v`. The `-v` switch will provide verbose information and will give more feedback on why NuGet wasn't able to install the `Microsoft.Windows.CppWinRT` library.
